// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.PayOnlinePage.clickSubmitFrm3D_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class clickSubmitFrm3D_Map:logWriter
    {
        
        /// <summary>
        /// clickSubmitFrm3D_Method
        /// </summary>
        public void clickSubmitFrm3D_Method()
        {
            #region Variable Declarations
            HtmlImage uIAcspa023133347227189Image = this.UIMasterCardSecureCodeWindow.UIMasterCardSecureCodeDocument.UITable2Table.UIAcspa023133347227189Image;
            #endregion

            // Click '/acs/pa/0/231333472271892037/auth_sc_submit.gif' image
            Mouse.Click(uIAcspa023133347227189Image, new Point(43, 12));
            WriteLogs("PASS : Clicked Submit Button From 3D Page. : VERIFICATION");
        }

        public Boolean Is3DPageOpened_Method()
        {
            #region Variable Declarations
            HtmlImage uIAcspa023133347227189Image = this.UIMasterCardSecureCodeWindow.UIMasterCardSecureCodeDocument.UITable2Table.UIAcspa023133347227189Image;
            #endregion

            Boolean Is3DPageOpened = false;
            uIAcspa023133347227189Image.WaitForControlExist(30000);
            Is3DPageOpened = uIAcspa023133347227189Image.TryFind();

            return Is3DPageOpened;
        }
        
        #region Properties
        public UIMasterCardSecureCodeWindow UIMasterCardSecureCodeWindow
        {
            get
            {
                if ((this.mUIMasterCardSecureCodeWindow == null))
                {
                    this.mUIMasterCardSecureCodeWindow = new UIMasterCardSecureCodeWindow();
                }
                return this.mUIMasterCardSecureCodeWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMasterCardSecureCodeWindow mUIMasterCardSecureCodeWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMasterCardSecureCodeWindow : BrowserWindow
    {
        
        public UIMasterCardSecureCodeWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "MasterCard® SecureCode™", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MasterCard® SecureCode™");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMasterCardSecureCodeDocument UIMasterCardSecureCodeDocument
        {
            get
            {
                if ((this.mUIMasterCardSecureCodeDocument == null))
                {
                    this.mUIMasterCardSecureCodeDocument = new UIMasterCardSecureCodeDocument(this);
                }
                return this.mUIMasterCardSecureCodeDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMasterCardSecureCodeDocument mUIMasterCardSecureCodeDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMasterCardSecureCodeDocument : HtmlDocument
    {
        
        public UIMasterCardSecureCodeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "MasterCard® SecureCode™", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/acs/pa/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/acs/pa/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MasterCard® SecureCode™");
            #endregion
        }
        
        #region Properties
        public UITable2Table UITable2Table
        {
            get
            {
                if ((this.mUITable2Table == null))
                {
                    this.mUITable2Table = new UITable2Table(this);
                }
                return this.mUITable2Table;
            }
        }
        #endregion
        
        #region Fields
        private UITable2Table mUITable2Table;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITable2Table : HtmlTable
    {
        
        public UITable2Table(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "table2";
            this.FilterProperties.Add(new PropertyExpression(HtmlTable.PropertyNames.InnerText, "One-Time Passcode Problem? Synchronize y", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlTable.PropertyNames.ControlDefinition, "id=table2 cellSpacing=0 cellPadding=0 width=\"100%\" border=0", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.WindowTitles.Add("MasterCard® SecureCode™");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIAcspa023133347227189Image
        {
            get
            {
                if ((this.mUIAcspa023133347227189Image == null))
                {
                    this.mUIAcspa023133347227189Image = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIAcspa023133347227189Image.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIAcspa023133347227189Image.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIAcspa023133347227189Image.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIAcspa023133347227189Image.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.AbsolutePath, "/auth_sc_submit.gif", PropertyExpressionOperator.Contains));
                    this.mUIAcspa023133347227189Image.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "/auth_sc_submit.gif", PropertyExpressionOperator.Contains));
                    this.mUIAcspa023133347227189Image.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.LinkAbsolutePath, "/acs/pa/", PropertyExpressionOperator.Contains));
                    this.mUIAcspa023133347227189Image.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Href, "/acs/pa/", PropertyExpressionOperator.Contains));
                    this.mUIAcspa023133347227189Image.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "onclick=\"submitAction();return false;\" b";
                    this.mUIAcspa023133347227189Image.WindowTitles.Add("MasterCard® SecureCode™");
                    #endregion
                }
                return this.mUIAcspa023133347227189Image;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIAcspa023133347227189Image;
        #endregion
    }
}
