// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.PayOnlinePage.selectCountry_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class selectCountry_Map:logWriter
    {
        
        /// <summary>
        /// selectCountry_Method - Use 'selectCountry_MethodParams' to pass parameters into this method.
        /// </summary>
        public void selectCountry_Method(string CountrytobeSelected)
        {
            #region Variable Declarations
            HtmlComboBox uIDdlCountryComboBox = this.UIPayOnlineWindowsInteWindow.UIPayOnlineDocument.UIDdlCountryComboBox;
            #endregion

            try
            {
                // Select 'United Kingdom' in 'ddlCountry' combo box
                //uIDdlCountryComboBox.SelectedItem = this.selectCountry_MethodParams.UIDdlCountryComboBoxSelectedItem;
                uIDdlCountryComboBox.SelectedItem = CountrytobeSelected;
                WriteLogs("PASS : Selected \""+uIDdlCountryComboBox.SelectedItem+"\" as Country.");
            }
            catch (AssertFailedException ex)
            {
                takeImage("selectCountry");
                WriteLogs("FAIL : Could not select Country From Pay Online Page.");
                WriteLogs("-----------------" + ex.Message.ToString());
            }
        }

        public void VerifyCountryBoxEnabled_Method()
        {
            #region Variable Declarations
            HtmlComboBox uIDdlCountryComboBox = this.UIPayOnlineWindowsInteWindow.UIPayOnlineDocument.UIDdlCountryComboBox;
            #endregion

            try
            {
                Boolean IsCountryBoxEnabled = uIDdlCountryComboBox.Enabled;
                if (IsCountryBoxEnabled == true)
                {
                    WriteLogs("PASS : Country List Box is Enabled.");
                }
                else
                {
                    WriteLogs("FAIL : Country List Box is Not Enabled.");
                }
             }
            catch (AssertFailedException ex)
            {
                takeImage("VerifyCountryBoxEnabled");
                WriteLogs("FAIL : Country List Box is Not Enabled.");
                WriteLogs("-----------------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public virtual selectCountry_MethodParams selectCountry_MethodParams
        {
            get
            {
                if ((this.mselectCountry_MethodParams == null))
                {
                    this.mselectCountry_MethodParams = new selectCountry_MethodParams();
                }
                return this.mselectCountry_MethodParams;
            }
        }
        
        public UIPayOnlineWindowsInteWindow UIPayOnlineWindowsInteWindow
        {
            get
            {
                if ((this.mUIPayOnlineWindowsInteWindow == null))
                {
                    this.mUIPayOnlineWindowsInteWindow = new UIPayOnlineWindowsInteWindow();
                }
                return this.mUIPayOnlineWindowsInteWindow;
            }
        }
        #endregion
        
        #region Fields
        private selectCountry_MethodParams mselectCountry_MethodParams;
        
        private UIPayOnlineWindowsInteWindow mUIPayOnlineWindowsInteWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'selectCountry_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class selectCountry_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'United Kingdom' in 'ddlCountry' combo box
        /// </summary>
        public string UIDdlCountryComboBoxSelectedItem = "United Kingdom";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIPayOnlineWindowsInteWindow : BrowserWindow
    {
        
        public UIPayOnlineWindowsInteWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Pay Online", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Pay Online");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIPayOnlineDocument UIPayOnlineDocument
        {
            get
            {
                if ((this.mUIPayOnlineDocument == null))
                {
                    this.mUIPayOnlineDocument = new UIPayOnlineDocument(this);
                }
                return this.mUIPayOnlineDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIPayOnlineDocument mUIPayOnlineDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIPayOnlineDocument : HtmlDocument
    {
        
        public UIPayOnlineDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Pay Online", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/booking/payonline.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/payonline.aspx", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Pay Online");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIDdlCountryComboBox
        {
            get
            {
                if ((this.mUIDdlCountryComboBox == null))
                {
                    this.mUIDdlCountryComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIDdlCountryComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ctl00_Placeholder1_addresscontrol_ddlCountry";
                    this.mUIDdlCountryComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$Placeholder1$addresscontrol$ddlCountry";
                    this.mUIDdlCountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "aspNetDisabled td_small";
                    this.mUIDdlCountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ctl00$Placeholder1$addresscontrol$";
                    this.mUIDdlCountryComboBox.WindowTitles.Add("Pay Online");
                    #endregion
                }
                return this.mUIDdlCountryComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIDdlCountryComboBox;
        #endregion
    }
}
