// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.BookingPages.AddAmendVillaExtras.selectVExtrasfrmChkBox_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class selectVExtrasfrmChkBox_Map:logWriter
    {
        
        /// <summary>
        /// selectVExtrasfrmChkBox_Method - Use 'selectVExtrasfrmChkBox_MethodParams' to pass parameters into this method.
        /// </summary>
        public void selectVExtrasfrmChkBox_Method()
        {
            #region Variable Declarations
            HtmlCheckBox uICtl00ContentPlaceHolCheckBox = this.UIYourHolidaySummaryWiWindow.UIYourHolidaySummaryDocument.UIAmendVillaExtrasSeleFrame.UIVillaPlusPackageHoliDocument.UICtl00ContentPlaceHolCheckBox;
            #endregion

            Boolean IsCheckBoxthere = uICtl00ContentPlaceHolCheckBox.TryFind();

            if (IsCheckBoxthere == true)
            {
                try
                {
                    UITestControlCollection VExtrasCheckBoxestoSelect = uICtl00ContentPlaceHolCheckBox.FindMatchingControls();
                    foreach (HtmlCheckBox ChkBox in VExtrasCheckBoxestoSelect)
                    {
                        if (ChkBox.Enabled == true)
                        {
                            Boolean ischckboxchecked = ChkBox.Checked;
                            if (ischckboxchecked == true)
                            {
                                ChkBox.SetProperty("checked", false);
                                WriteLogs("PASS : Check Box is De-Selected for listed Villa Extra.");
                            }
                            else
                            {
                                ChkBox.SetProperty("checked", true);
                                WriteLogs("PASS : Check Box is Selected for listed Villa Extra.");
                            }
                        }
                        else
                        {
                            WriteLogs("PASS : The Check Box is Disabled and Could Not Select a Qty.");
                        }
                        WriteLogs("PASS : Quantity is Selected for all the listed Villa Extras.");
                    }
                }
                catch (AssertFailedException ex)
                {
                    takeImage("selectVExtrasfrmChkBox");
                    WriteLogs("FAIL : Could Not Select Quantity check Box for all/Few of the listed Villa Extras.");
                    WriteLogs("-----------------" + ex.Message.ToString());
                }

                // Select 'ctl00$ContentPlaceHolder1$rept1$ctl01$chkSelect' check box
                //uICtl00ContentPlaceHolCheckBox.Checked = this.selectVExtrasfrmChkBox_MethodParams.UICtl00ContentPlaceHolCheckBoxChecked;
            }
        }

        public Boolean IsVExtrasCHKboxthere_Method()
        {
            #region Variable Declarations
            HtmlCheckBox uICtl00ContentPlaceHolCheckBox = this.UIYourHolidaySummaryWiWindow.UIYourHolidaySummaryDocument.UIAmendVillaExtrasSeleFrame.UIVillaPlusPackageHoliDocument.UICtl00ContentPlaceHolCheckBox;
            #endregion

            Boolean IsCheckBoxthere = false;
            IsCheckBoxthere = uICtl00ContentPlaceHolCheckBox.TryFind();
            
            if (IsCheckBoxthere == true)
            {
                IsCheckBoxthere = true;
            }
            else
            {
                IsCheckBoxthere = false;
            }

            return IsCheckBoxthere;
        }
        
        #region Properties
        public virtual selectVExtrasfrmChkBox_MethodParams selectVExtrasfrmChkBox_MethodParams
        {
            get
            {
                if ((this.mselectVExtrasfrmChkBox_MethodParams == null))
                {
                    this.mselectVExtrasfrmChkBox_MethodParams = new selectVExtrasfrmChkBox_MethodParams();
                }
                return this.mselectVExtrasfrmChkBox_MethodParams;
            }
        }
        
        public UIYourHolidaySummaryWiWindow UIYourHolidaySummaryWiWindow
        {
            get
            {
                if ((this.mUIYourHolidaySummaryWiWindow == null))
                {
                    this.mUIYourHolidaySummaryWiWindow = new UIYourHolidaySummaryWiWindow();
                }
                return this.mUIYourHolidaySummaryWiWindow;
            }
        }
        #endregion
        
        #region Fields
        private selectVExtrasfrmChkBox_MethodParams mselectVExtrasfrmChkBox_MethodParams;
        
        private UIYourHolidaySummaryWiWindow mUIYourHolidaySummaryWiWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'selectVExtrasfrmChkBox_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class selectVExtrasfrmChkBox_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'ctl00$ContentPlaceHolder1$rept1$ctl01$chkSelect' check box
        /// </summary>
        public bool UICtl00ContentPlaceHolCheckBoxChecked = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIYourHolidaySummaryWiWindow : BrowserWindow
    {
        
        public UIYourHolidaySummaryWiWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Your Holiday Summary", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYourHolidaySummaryDocument UIYourHolidaySummaryDocument
        {
            get
            {
                if ((this.mUIYourHolidaySummaryDocument == null))
                {
                    this.mUIYourHolidaySummaryDocument = new UIYourHolidaySummaryDocument(this);
                }
                return this.mUIYourHolidaySummaryDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYourHolidaySummaryDocument mUIYourHolidaySummaryDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIYourHolidaySummaryDocument : HtmlDocument
    {
        
        public UIYourHolidaySummaryDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Your Holiday Summary", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/booking/default.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/default.aspx", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public UIAmendVillaExtrasSeleFrame UIAmendVillaExtrasSeleFrame
        {
            get
            {
                if ((this.mUIAmendVillaExtrasSeleFrame == null))
                {
                    this.mUIAmendVillaExtrasSeleFrame = new UIAmendVillaExtrasSeleFrame(this);
                }
                return this.mUIAmendVillaExtrasSeleFrame;
            }
        }
        #endregion
        
        #region Fields
        private UIAmendVillaExtrasSeleFrame mUIAmendVillaExtrasSeleFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAmendVillaExtrasSeleFrame : HtmlIFrame
    {
        
        public UIAmendVillaExtrasSeleFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "amendVillaExtrasSelection";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = "amendVillaExtrasSelection";
            this.FilterProperties.Add(new PropertyExpression(HtmlFrame.PropertyNames.AbsolutePath, "amendVillaExtra.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlFrame.PropertyNames.PageUrl, "amendVillaExtra.aspx?", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "name=\"amendVillaExtrasSelection\" id=\"ame";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public UIVillaPlusPackageHoliDocument UIVillaPlusPackageHoliDocument
        {
            get
            {
                if ((this.mUIVillaPlusPackageHoliDocument == null))
                {
                    this.mUIVillaPlusPackageHoliDocument = new UIVillaPlusPackageHoliDocument(this);
                }
                return this.mUIVillaPlusPackageHoliDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusPackageHoliDocument mUIVillaPlusPackageHoliDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaPlusPackageHoliDocument : HtmlDocument
    {
        
        public UIVillaPlusPackageHoliDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/booking/amendVillaExtra.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/amendVillaExtra.aspx?", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public HtmlCheckBox UICtl00ContentPlaceHolCheckBox
        {
            get
            {
                if ((this.mUICtl00ContentPlaceHolCheckBox == null))
                {
                    this.mUICtl00ContentPlaceHolCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceHolCheckBox.SearchProperties.Add(new PropertyExpression(HtmlCheckBox.PropertyNames.Id, "ctl00_ContentPlaceHolder1_rept1_", PropertyExpressionOperator.Contains));
                    this.mUICtl00ContentPlaceHolCheckBox.SearchProperties.Add(new PropertyExpression(HtmlCheckBox.PropertyNames.Name, "ctl00$ContentPlaceHolder1$rept1$", PropertyExpressionOperator.Contains));
                    this.mUICtl00ContentPlaceHolCheckBox.FilterProperties.Add(new PropertyExpression(HtmlCheckBox.PropertyNames.ControlDefinition, "name=\"ctl00$ContentPlaceHolder1$rept1$", PropertyExpressionOperator.Contains));
                    this.mUICtl00ContentPlaceHolCheckBox.WindowTitles.Add("Your Holiday Summary");
                    #endregion
                }
                return this.mUICtl00ContentPlaceHolCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCheckBox mUICtl00ContentPlaceHolCheckBox;
        #endregion
    }
}
