// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.HomePage.clickImageHeatedPools_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickImageHeatedPools_Map:logWriter
    {
        
        /// <summary>
        /// clickImageHeatedPools_Method
        /// </summary>
        public void clickImageHeatedPools_Method()
        {
            #region Variable Declarations
            HtmlDiv uIItemPane = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument1.UISmallCarouselDotNavsPane.UIItemPane;
            HtmlImage uIThinkVillasWithHeateImage = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument1.UISmallCarouselSlidePane.UIThinkVillasWithHeateImage;
            #endregion

            //Playback.Wait(1000);
            // Click pane
            Mouse.Click(uIItemPane, new Point(4, 2));
            //Playback.Wait(1000);
            // Click 'Think Villas With Heated Pools' image
            Mouse.Click(uIThinkVillasWithHeateImage, new Point(161, 47));
            string chkURL = null;
            try
            {
                StringAssert.Contains(chkURL, "villas-with-heated-pools");
                WriteLogs("PASS : Clicked on Heated Pools Image from the Carouse 2nd Banner.");

            }
            catch (Exception ex)
            {

                WriteLogs("FAIL : Clicked on Heated Pools Image from the Carouse 2nd Banner.");
                WriteLogs("----------" + ex.Message.ToString());
            }
            this.UIVillaHolidaysThatYouWindow.Back();
        }
        
        #region Properties
        public UIVillaHolidaysThatYouWindow UIVillaHolidaysThatYouWindow
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouWindow == null))
                {
                    this.mUIVillaHolidaysThatYouWindow = new UIVillaHolidaysThatYouWindow();
                }
                return this.mUIVillaHolidaysThatYouWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouWindow mUIVillaHolidaysThatYouWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouWindow : BrowserWindow
    {
        
        public UIVillaHolidaysThatYouWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaHolidaysThatYouDocument UIVillaHolidaysThatYouDocument
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument == null))
                {
                    this.mUIVillaHolidaysThatYouDocument = new UIVillaHolidaysThatYouDocument(this);
                }
                return this.mUIVillaHolidaysThatYouDocument;
            }
        }
        
        public UIVillaHolidaysThatYouDocument1 UIVillaHolidaysThatYouDocument1
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument1 == null))
                {
                    this.mUIVillaHolidaysThatYouDocument1 = new UIVillaHolidaysThatYouDocument1(this);
                }
                return this.mUIVillaHolidaysThatYouDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouDocument mUIVillaHolidaysThatYouDocument;
        
        private UIVillaHolidaysThatYouDocument1 mUIVillaHolidaysThatYouDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouDocument : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UISmallCarouselSlidePane UISmallCarouselSlidePane
        {
            get
            {
                if ((this.mUISmallCarouselSlidePane == null))
                {
                    this.mUISmallCarouselSlidePane = new UISmallCarouselSlidePane(this);
                }
                return this.mUISmallCarouselSlidePane;
            }
        }
        
        public UISmallCarouselDotNavsPane UISmallCarouselDotNavsPane
        {
            get
            {
                if ((this.mUISmallCarouselDotNavsPane == null))
                {
                    this.mUISmallCarouselDotNavsPane = new UISmallCarouselDotNavsPane(this);
                }
                return this.mUISmallCarouselDotNavsPane;
            }
        }
        #endregion
        
        #region Fields
        private UISmallCarouselSlidePane mUISmallCarouselSlidePane;
        
        private UISmallCarouselDotNavsPane mUISmallCarouselDotNavsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISmallCarouselSlidePane : HtmlDiv
    {
        
        public UISmallCarouselSlidePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "smallCarouselSlide";
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "aRow";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"aRow\" id=\"smallCarouselSlide\"", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIThinkVillasWithHeateImage
        {
            get
            {
                if ((this.mUIThinkVillasWithHeateImage == null))
                {
                    this.mUIThinkVillasWithHeateImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIThinkVillasWithHeateImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Think Villas With Heated Pools";
                    this.mUIThinkVillasWithHeateImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.AbsolutePath, "/images/common/home_HeatedPools.jpg", PropertyExpressionOperator.Contains));
                    this.mUIThinkVillasWithHeateImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "/images/common/home_HeatedPools.jpg", PropertyExpressionOperator.Contains));
                    this.mUIThinkVillasWithHeateImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.ControlDefinition, "title=\"Think Vi", PropertyExpressionOperator.Contains));
                    this.mUIThinkVillasWithHeateImage.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIThinkVillasWithHeateImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIThinkVillasWithHeateImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISmallCarouselDotNavsPane : HtmlDiv
    {
        
        public UISmallCarouselDotNavsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "smallCarouselDotNavs";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"smallCarouselDotNavs\"";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "smallCarouselCurrentDot";
                    this.mUIItemPane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"smallCarouselCurrentDot\" data-bannerIndex=\"1\"", PropertyExpressionOperator.Contains));
                    this.mUIItemPane.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouDocument1 : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UISmallCarouselDotNavsPane1 UISmallCarouselDotNavsPane
        {
            get
            {
                if ((this.mUISmallCarouselDotNavsPane == null))
                {
                    this.mUISmallCarouselDotNavsPane = new UISmallCarouselDotNavsPane1(this);
                }
                return this.mUISmallCarouselDotNavsPane;
            }
        }
        
        public UISmallCarouselSlidePane1 UISmallCarouselSlidePane
        {
            get
            {
                if ((this.mUISmallCarouselSlidePane == null))
                {
                    this.mUISmallCarouselSlidePane = new UISmallCarouselSlidePane1(this);
                }
                return this.mUISmallCarouselSlidePane;
            }
        }
        #endregion
        
        #region Fields
        private UISmallCarouselDotNavsPane1 mUISmallCarouselDotNavsPane;
        
        private UISmallCarouselSlidePane1 mUISmallCarouselSlidePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISmallCarouselDotNavsPane1 : HtmlDiv
    {
        
        public UISmallCarouselDotNavsPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "smallCarouselDotNavs";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"smallCarouselDotNavs\"";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "smallCarouselDot";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"smallCarouselDot\" data-bannerIndex=\"1\"";
                    this.mUIItemPane.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISmallCarouselSlidePane1 : HtmlDiv
    {
        
        public UISmallCarouselSlidePane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "smallCarouselSlide";
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "aRow";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"aRow\" id=\"smallCarouselSlide\"", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIThinkVillasWithHeateImage
        {
            get
            {
                if ((this.mUIThinkVillasWithHeateImage == null))
                {
                    this.mUIThinkVillasWithHeateImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIThinkVillasWithHeateImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Think Villas With Heated Pools";
                    this.mUIThinkVillasWithHeateImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.AbsolutePath, "/images/common/home_HeatedPools.jpg", PropertyExpressionOperator.Contains));
                    this.mUIThinkVillasWithHeateImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "/images/common/home_HeatedPools.jpg", PropertyExpressionOperator.Contains));
                    this.mUIThinkVillasWithHeateImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.ControlDefinition, "title=\"Think Vi", PropertyExpressionOperator.Contains));
                    this.mUIThinkVillasWithHeateImage.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIThinkVillasWithHeateImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIThinkVillasWithHeateImage;
        #endregion
    }
}
