// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.HomePage.ClickCostaBlancaLink_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class ClickCostaBlancaLink_Map:logWriter
    {
        
        /// <summary>
        /// ClickCostaBlancaLink_Method
        /// </summary>
        public void ClickCostaBlancaLink_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uICostaBlancaHyperlink = this.UIHomePageWindowsInterWindow.UIHomePageDocument.UICostaBlancaPane.UICostaBlancaHyperlink;
            #endregion

            // Click 'Costa Blanca' link
            Mouse.Click(uICostaBlancaHyperlink, new Point(46, 7));
            String cmprcostablanca = this.UIHomePageWindowsInterWindow.Uri.ToString();
            try
            {
                StringAssert.Contains(cmprcostablanca, "costablanca");
                WriteLogs("PASS : Verify Costa Blanca Villa Lists Page.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Verify Costa Blanca Villa Lists Page.");
                WriteLogs("-------EXCEPTION-------" + ex.Message.ToString());
            }
            //if (cmprcostablanca.Contains("costablanca"))
            //{
            //    WriteLogs("Verify Costa Blanca Villa Lists Page : PASS");
            //}
            //else
            //{
            //    WriteLogs("Verify Costa Blanca Villa Lists Page : FAIL");
            //}
            this.UIHomePageWindowsInterWindow.Back();
        }
        
        #region Properties
        public UIHomePageWindowsInterWindow UIHomePageWindowsInterWindow
        {
            get
            {
                if ((this.mUIHomePageWindowsInterWindow == null))
                {
                    this.mUIHomePageWindowsInterWindow = new UIHomePageWindowsInterWindow();
                }
                return this.mUIHomePageWindowsInterWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageWindowsInterWindow mUIHomePageWindowsInterWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHomePageWindowsInterWindow : BrowserWindow
    {
        
        public UIHomePageWindowsInterWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Home Page", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageDocument UIHomePageDocument
        {
            get
            {
                if ((this.mUIHomePageDocument == null))
                {
                    this.mUIHomePageDocument = new UIHomePageDocument(this);
                }
                return this.mUIHomePageDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageDocument mUIHomePageDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHomePageDocument : HtmlDocument
    {
        
        public UIHomePageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "http://", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        #region Properties
        public UICostaBlancaPane UICostaBlancaPane
        {
            get
            {
                if ((this.mUICostaBlancaPane == null))
                {
                    this.mUICostaBlancaPane = new UICostaBlancaPane(this);
                }
                return this.mUICostaBlancaPane;
            }
        }
        #endregion
        
        #region Fields
        private UICostaBlancaPane mUICostaBlancaPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICostaBlancaPane : HtmlDiv
    {
        
        public UICostaBlancaPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Id, "destBL", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Costa Blanca";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "id=destBL", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "91";
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICostaBlancaHyperlink
        {
            get
            {
                if ((this.mUICostaBlancaHyperlink == null))
                {
                    this.mUICostaBlancaHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICostaBlancaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICostaBlancaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICostaBlancaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICostaBlancaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Costa Blanca";
                    this.mUICostaBlancaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/costablanca/code_net/villas/villalists.aspx";
                    this.mUICostaBlancaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICostaBlancaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://nimbus/costablanca/code_net/villas/villalists.aspx";
                    this.mUICostaBlancaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICostaBlancaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/costablanca/code_net/villas/villa";
                    this.mUICostaBlancaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUICostaBlancaHyperlink.WindowTitles.Add("Home Page");
                    #endregion
                }
                return this.mUICostaBlancaHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICostaBlancaHyperlink;
        #endregion
    }
}
