// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.HomePage.clickImageWiFi_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickImageWiFi_Map:logWriter
    {
        
        /// <summary>
        /// clickImageWiFi_Method
        /// </summary>
        public void clickImageWiFi_Method()
        {
            #region Variable Declarations
            HtmlDiv uIItemPane = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UISmallCarouselDotNavsPane.UIItemPane;
            HtmlImage uIThinkWiFiImage = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UISmallCarouselSlidePane.UIThinkWiFiImage;
            #endregion

            //Playback.Wait(1000);
            // Click pane
            Mouse.Click(uIItemPane, new Point(6, 3));
            //Playback.Wait(1000);
            // Click 'Think WiFi' image
            Mouse.Click(uIThinkWiFiImage, new Point(213, 61));
            string chkURL = this.UIVillaHolidaysThatYouWindow.Uri.ToString();

            try
            {
                StringAssert.Contains(chkURL, "villas-with-wifi");
                WriteLogs("PASS : Clicked o Wifi Villas Image from Carouse Banner.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Clicked o Wifi Villas Image from Carouse Banner.");
                WriteLogs("--------" + ex.Message.ToString());
            }
            this.UIVillaHolidaysThatYouWindow.Back();
        }
        
        #region Properties
        public UIVillaHolidaysThatYouWindow UIVillaHolidaysThatYouWindow
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouWindow == null))
                {
                    this.mUIVillaHolidaysThatYouWindow = new UIVillaHolidaysThatYouWindow();
                }
                return this.mUIVillaHolidaysThatYouWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouWindow mUIVillaHolidaysThatYouWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouWindow : BrowserWindow
    {
        
        public UIVillaHolidaysThatYouWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaHolidaysThatYouDocument UIVillaHolidaysThatYouDocument
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument == null))
                {
                    this.mUIVillaHolidaysThatYouDocument = new UIVillaHolidaysThatYouDocument(this);
                }
                return this.mUIVillaHolidaysThatYouDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouDocument mUIVillaHolidaysThatYouDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouDocument : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UISmallCarouselDotNavsPane UISmallCarouselDotNavsPane
        {
            get
            {
                if ((this.mUISmallCarouselDotNavsPane == null))
                {
                    this.mUISmallCarouselDotNavsPane = new UISmallCarouselDotNavsPane(this);
                }
                return this.mUISmallCarouselDotNavsPane;
            }
        }
        
        public UISmallCarouselSlidePane UISmallCarouselSlidePane
        {
            get
            {
                if ((this.mUISmallCarouselSlidePane == null))
                {
                    this.mUISmallCarouselSlidePane = new UISmallCarouselSlidePane(this);
                }
                return this.mUISmallCarouselSlidePane;
            }
        }
        #endregion
        
        #region Fields
        private UISmallCarouselDotNavsPane mUISmallCarouselDotNavsPane;
        
        private UISmallCarouselSlidePane mUISmallCarouselSlidePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISmallCarouselDotNavsPane : HtmlDiv
    {
        
        public UISmallCarouselDotNavsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "smallCarouselDotNavs";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"smallCarouselDotNavs\"";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "smallCarouselDot";
                    this.mUIItemPane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"smallCarouselDot\" data-bannerIndex=\"2\"", PropertyExpressionOperator.Contains));
                    this.mUIItemPane.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISmallCarouselSlidePane : HtmlDiv
    {
        
        public UISmallCarouselSlidePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "smallCarouselSlide";
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "aRow";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"aRow\" id=\"smallCarouselSlide\"", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIThinkWiFiImage
        {
            get
            {
                if ((this.mUIThinkWiFiImage == null))
                {
                    this.mUIThinkWiFiImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIThinkWiFiImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Think WiFi";
                    this.mUIThinkWiFiImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.AbsolutePath, "/images/common/home_VeryVilla.jpg", PropertyExpressionOperator.Contains));
                    this.mUIThinkWiFiImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "/images/common/home_VeryVilla.jpg", PropertyExpressionOperator.Contains));
                    this.mUIThinkWiFiImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.ControlDefinition, "title=\"Think WiFi\" style=\"display: ", PropertyExpressionOperator.Contains));
                    this.mUIThinkWiFiImage.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIThinkWiFiImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIThinkWiFiImage;
        #endregion
    }
}
