// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.HomePage.ClickKefaloniaLink_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class ClickKefaloniaLink_Map:logWriter
    {
        
        /// <summary>
        /// ClickKefaloniaLink_Method
        /// </summary>
        public void ClickKefaloniaLink_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uIKefaloniaHyperlink = this.UIHomePageWindowsInterWindow.UIHomePageDocument.UIKefaloniaPane.UIKefaloniaHyperlink;
            #endregion

            // Click 'Kefalonia' link
            Mouse.Click(uIKefaloniaHyperlink, new Point(36, 4));
            String cmprkefalonia = this.UIHomePageWindowsInterWindow.Uri.ToString();
            try
            {
                StringAssert.Contains(cmprkefalonia, "kefalonia");
                WriteLogs("PASS : Kefalonia Villa Lists Page displayed.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Kefalonia Villa Lists Page not displayed.");
                WriteLogs("-------EXCEPTION-------" + ex.Message.ToString());
            }
            //if (cmprkefalonia.Contains("kefalonia")) 
            //{
            //    WriteLogs("Verify Kefalonia Villa Lists Page : PASS");
            //}
            //else
            //{
            //    WriteLogs("Verify Kefalonia Villa Lists Page : FAIL");
               
            //}
            this.UIHomePageWindowsInterWindow.Back();
        }
        
        #region Properties
        public UIHomePageWindowsInterWindow UIHomePageWindowsInterWindow
        {
            get
            {
                if ((this.mUIHomePageWindowsInterWindow == null))
                {
                    this.mUIHomePageWindowsInterWindow = new UIHomePageWindowsInterWindow();
                }
                return this.mUIHomePageWindowsInterWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageWindowsInterWindow mUIHomePageWindowsInterWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHomePageWindowsInterWindow : BrowserWindow
    {
        
        public UIHomePageWindowsInterWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Home Page", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageDocument UIHomePageDocument
        {
            get
            {
                if ((this.mUIHomePageDocument == null))
                {
                    this.mUIHomePageDocument = new UIHomePageDocument(this);
                }
                return this.mUIHomePageDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageDocument mUIHomePageDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHomePageDocument : HtmlDocument
    {
        
        public UIHomePageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://nimbus/";
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        #region Properties
        public UIKefaloniaPane UIKefaloniaPane
        {
            get
            {
                if ((this.mUIKefaloniaPane == null))
                {
                    this.mUIKefaloniaPane = new UIKefaloniaPane(this);
                }
                return this.mUIKefaloniaPane;
            }
        }
        #endregion
        
        #region Fields
        private UIKefaloniaPane mUIKefaloniaPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIKefaloniaPane : HtmlDiv
    {
        
        public UIKefaloniaPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Id, "destKE", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Kefalonia";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "id=destKE", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.TagInstance, "91", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIKefaloniaHyperlink
        {
            get
            {
                if ((this.mUIKefaloniaHyperlink == null))
                {
                    this.mUIKefaloniaHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIKefaloniaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Kefalonia";
                    this.mUIKefaloniaHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.AbsolutePath, "/villalists.aspx", PropertyExpressionOperator.Contains));
                    this.mUIKefaloniaHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.Href, "/villalists.aspx", PropertyExpressionOperator.Contains));
                    this.mUIKefaloniaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIKefaloniaHyperlink.WindowTitles.Add("Home Page");
                    #endregion
                }
                return this.mUIKefaloniaHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIKefaloniaHyperlink;
        #endregion
    }
}
