// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.HomePage.VerifyVillasFacilityText_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class VerifyVillasFacilityText_Map:logWriter
    {
        
        /// <summary>
        /// VerifyVillasFacilityText_Method - Use 'VerifyVillasFacilityText_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void VerifyVillasFacilityText_Method()
        {
            #region Variable Declarations
            HtmlDiv uIDvourVillaPane = this.UIHomePageWindowsInterWindow.UIHomePageDocument.UIDvourVillaPane;
            #endregion

            // Verify that the 'InnerText' property of 'dvourVilla' pane equals ' 
            //
            // Private Pools  Pool Table  Satellite TV (BBC/ITV in most resorts)  Air con/heating  Table Tennis Table  Dishwasher & Microwave!  Pool heating  BBQ  Friendly, knowledgeable UK staff  CD & DVD Player  Washing Machine  Maid & Linen service 
            //
            //
            // '
            string comapreStr1 = this.VerifyVillasFacilityText_MethodExpectedValues.UIDvourVillaPaneInnerText;
            comapreStr1 = comapreStr1.Trim();
            comapreStr1 = comapreStr1.Replace("\r\n", string.Empty);
            comapreStr1 = comapreStr1.Replace(" ", string.Empty);
            string comapreStr2 = uIDvourVillaPane.InnerText;
            comapreStr2 = comapreStr2.Trim();
            comapreStr2 = comapreStr2.Replace("\r\n", string.Empty);
            comapreStr2 = comapreStr2.Replace(" ", string.Empty);
            try
            {
                Assert.AreEqual(comapreStr1,comapreStr2);
                WriteLogs("PASS : Villa Facility Text.");
            }
            catch (AssertFailedException ex)
            {
                WriteLogs("FAIL : Villa Facility Text.");
                WriteLogs("-------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public virtual VerifyVillasFacilityText_MethodExpectedValues VerifyVillasFacilityText_MethodExpectedValues
        {
            get
            {
                if ((this.mVerifyVillasFacilityText_MethodExpectedValues == null))
                {
                    this.mVerifyVillasFacilityText_MethodExpectedValues = new VerifyVillasFacilityText_MethodExpectedValues();
                }
                return this.mVerifyVillasFacilityText_MethodExpectedValues;
            }
        }
        
        public UIHomePageWindowsInterWindow UIHomePageWindowsInterWindow
        {
            get
            {
                if ((this.mUIHomePageWindowsInterWindow == null))
                {
                    this.mUIHomePageWindowsInterWindow = new UIHomePageWindowsInterWindow();
                }
                return this.mUIHomePageWindowsInterWindow;
            }
        }
        #endregion
        
        #region Fields
        private VerifyVillasFacilityText_MethodExpectedValues mVerifyVillasFacilityText_MethodExpectedValues;
        
        private UIHomePageWindowsInterWindow mUIHomePageWindowsInterWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifyVillasFacilityText_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class VerifyVillasFacilityText_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'dvourVilla' pane equals ' 
        ///
        /// Private Pools  Pool Table  Satellite TV (BBC/ITV in most resorts)  Air con/heating  Table Tennis Table  Dishwasher & Microwave!  Pool heating  BBQ  Friendly, knowledgeable UK staff  CD & DVD Player  Washing Machine  Maid & Linen service 
        ///
        ///
        /// '
        /// </summary>
        public string UIDvourVillaPaneInnerText = " \r\n\r\n Private Pools  Pool Table  Satellite TV (BBC/ITV in most resorts)  Air con/" +
            "heating  Table Tennis Table  Dishwasher & Microwave!  Pool heating  BBQ  Friendl" +
            "y, knowledgeable UK staff  CD & DVD Player  Washing Machine  Maid & Linen servic" +
            "e \r\n\r\n\r\n ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHomePageWindowsInterWindow : BrowserWindow
    {
        
        public UIHomePageWindowsInterWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageDocument UIHomePageDocument
        {
            get
            {
                if ((this.mUIHomePageDocument == null))
                {
                    this.mUIHomePageDocument = new UIHomePageDocument(this);
                }
                return this.mUIHomePageDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageDocument mUIHomePageDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHomePageDocument : HtmlDocument
    {
        
        public UIHomePageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "http://", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Home Page");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIDvourVillaPane
        {
            get
            {
                if ((this.mUIDvourVillaPane == null))
                {
                    this.mUIDvourVillaPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDvourVillaPane.SearchProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Id, "dvourVilla", PropertyExpressionOperator.Contains));
                    this.mUIDvourVillaPane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, " \r\n\r\n Private Pools  Pool Table  Satelli", PropertyExpressionOperator.Contains));
                    this.mUIDvourVillaPane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "id=dvourVilla", PropertyExpressionOperator.Contains));
                    this.mUIDvourVillaPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "47";
                    this.mUIDvourVillaPane.WindowTitles.Add("Home Page");
                    #endregion
                }
                return this.mUIDvourVillaPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIDvourVillaPane;
        #endregion
    }
}
