// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.BookingPages.clickYesFrmCheckInBags_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class clickYesFrmCheckInBags_Map:logWriter
    {
        
        /// <summary>
        /// clickYesFrmCheckInBags_Method
        /// </summary>
        public void clickYesFrmCheckInBags_Method()
        {
            #region Variable Declarations
            HtmlImage uIYesImage = this.UIYourHolidaySummaryInWindow.UIYourHolidaySummaryDocument.UIYesImage;
            #endregion

            try
            {
                Mouse.Click(uIYesImage);
                WriteLogs("PASS : Clicked 'YES' button from Hold Items Popup.");
            }
            catch (AssertFailedException ex)
            {
                takeImage("clickYesFrmCheck-InBags");
                WriteLogs("FAIL : Could not click 'YES' button from Check-In Bags Popup.");
                WriteLogs("-----------------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIYourHolidaySummaryInWindow UIYourHolidaySummaryInWindow
        {
            get
            {
                if ((this.mUIYourHolidaySummaryInWindow == null))
                {
                    this.mUIYourHolidaySummaryInWindow = new UIYourHolidaySummaryInWindow();
                }
                return this.mUIYourHolidaySummaryInWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYourHolidaySummaryInWindow mUIYourHolidaySummaryInWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIYourHolidaySummaryInWindow : BrowserWindow
    {
        
        public UIYourHolidaySummaryInWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Your Holiday Summary";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYourHolidaySummaryDocument UIYourHolidaySummaryDocument
        {
            get
            {
                if ((this.mUIYourHolidaySummaryDocument == null))
                {
                    this.mUIYourHolidaySummaryDocument = new UIYourHolidaySummaryDocument(this);
                }
                return this.mUIYourHolidaySummaryDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYourHolidaySummaryDocument mUIYourHolidaySummaryDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIYourHolidaySummaryDocument : HtmlDocument
    {
        
        public UIYourHolidaySummaryDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Your Holiday Summary";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/default.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/default.aspx", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIYesImage
        {
            get
            {
                if ((this.mUIYesImage == null))
                {
                    this.mUIYesImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIYesImage.SearchProperties[HtmlImage.PropertyNames.Id] = "cmdYes";
                    this.mUIYesImage.SearchProperties[HtmlImage.PropertyNames.Name] = "cmdYes";
                    this.mUIYesImage.FilterProperties[HtmlImage.PropertyNames.Alt] = "Yes";
                    this.mUIYesImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/imgs/vp/buttons/yesOFF.gif";
                    this.mUIYesImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "/imgs/vp/buttons/yesOFF.gif", PropertyExpressionOperator.Contains));
                    this.mUIYesImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.ControlDefinition, "name=\"cmdYes\" id=\"cmdYes\"", PropertyExpressionOperator.Contains));
                    this.mUIYesImage.WindowTitles.Add("Your Holiday Summary");
                    #endregion
                }
                return this.mUIYesImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIYesImage;
        #endregion
    }
}
