// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.ProductPage.verifyHSPKOpened_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public partial class verifyHSPKOpened_Map:logWriter
    {
        
        /// <summary>
        /// verifyHSPKOpened_Method - Use 'verifyHSPKOpened_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyHSPKOpened_Method(string VillaFULLNAME, string BOOKINGID)
        {
            #region Variable Declarations
            HtmlDiv uIYourHolidaySummaryPane = this.UIYourHolidaySummaryWiWindow.UIYourHolidaySummaryDocument.UITblMainTable.UIYourHolidaySummaryPane;
            #endregion

            //// Verify that the 'InnerText' property of 'Your Holiday Summary' pane equals 'Your Holiday Summary'
            //Assert.AreEqual(this.verifyHSPKOpened_MethodExpectedValues.UIYourHolidaySummaryPaneInnerText, uIYourHolidaySummaryPane.InnerText);
            try
            {
                Assert.AreEqual(this.verifyHSPKOpened_MethodExpectedValues.UIYourHolidaySummaryPaneInnerText, uIYourHolidaySummaryPane.InnerText);
                WriteLogs("PASS : HS Page for \"" + VillaFULLNAME + "\" with Booking ID \"" + BOOKINGID + "\" is Opened. : VERIFICATION");
            }
            catch (AssertFailedException ex)
            {
                takeImage("verifyHSPKOpened");
                WriteLogs("FAIL : HS Page for \"(" + VillaFULLNAME + ")\" is not Opened. : VERIFICATION");
                WriteLogs("-----------------" + ex.Message.ToString());
            }
        }

        //public string getBookingID()
        //{
        //    string Str = this.UIYourHolidaySummaryWiWindow.UIYourHolidaySummaryDocument.GetProperty("outerHtml").ToString();
        //    string findString = "hdnBookingId";
        //    int index = Str.IndexOf(findString);
        //    if (index == -1)
        //    {
        //        findString = "<INPUT id=hdnBookingId name=hdnBookingId value=";
        //        index = Str.IndexOf(findString);
        //    }

        //    return "BookingID";
        //}

        //public string getBookingID()
        //{
        //    string str = this.UIYourHolidaySummaryWiWindow.UIYourHolidaySummaryDocument.GetProperty("OuterHtml").ToString();
        //    string findString = "<input name=\"hdnBookingId\" id=\"hdnBookingId\" type=\"hidden\" value=";
            
        //    int index = str.IndexOf(findString);
        //    if (index == -1)
        //    {
        //        findString = "<INPUT id=hdnBookingId name=hdnBookingId value=";
        //        index = str.IndexOf(findString);
        //    }
        //    //string bookingIDstr = str.Substring(index, 55);
        //    string bookingIDstrtmp = str.Substring(index);
        //    int index1 = bookingIDstrtmp.IndexOf(">");
        //    string bookingIDstr = bookingIDstrtmp.Substring(0, index1);
        //    string bookingIDstr1 = bookingIDstr.Replace("/", "'");
        //    string[] bookidarr = bookingIDstr1.Split(' ');
        //    string bookingIDtmp = bookidarr[4];
        //    //string bookingIDtmp1 = bookingIDtmp.Replace("/","''");
        //    string[] bookingID = bookingIDtmp.Split('=');
        //    return bookingID[1];
        //}

        public string getBookingID(string strURL)
        {
            delayExecution(strURL);
            string str = string.Empty;
            string bookingID = string.Empty;
            int count = 0;
            do
            {
                try
                {
                    str = this.UIYourHolidaySummaryWiWindow.UIYourHolidaySummaryDocument.GetProperty("OuterHtml").ToString();
                    string regexBookingId = @"<input[\s]+[^>]*?name[\s]?=[\s""']+(hdnBookingId)[\s""']+id[\s]?=[\s""']+(hdnBookingId)[\s""']+type[\s]?=[\s""']+(hidden)[\s""']+value[\s]?=[\s""']+(.*?)[""']+.*?>";
                    Regex exBookingId = new Regex(regexBookingId, RegexOptions.IgnoreCase);
                    string bookingIDstrtmp = exBookingId.Match(str).Value.Trim().ToString();
                    string[] bookidarr = bookingIDstrtmp.Split('=');
                    bookingID = bookidarr[4];
                    bookingID = bookingID.TrimStart('"');
                    bookingID = bookingID.Remove(bookingID.Length - 2);
                }
                catch (Exception ex)
                {
                    ex.Message.ToString();
                    count = count+1;
                }
            } while (bookingID == "" && count <= 5);
            if (bookingID == "")
            {
                WriteLogs("FAIL : Could not find BookingID From HS Page. : VERIFICATION");
                takeImage("BookingID_HSPage.");
            }
           
            return bookingID;
        }

        

        
        #region Properties
        public virtual verifyHSPKOpened_MethodExpectedValues verifyHSPKOpened_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyHSPKOpened_MethodExpectedValues == null))
                {
                    this.mverifyHSPKOpened_MethodExpectedValues = new verifyHSPKOpened_MethodExpectedValues();
                }
                return this.mverifyHSPKOpened_MethodExpectedValues;
            }
        }
        
        public UIYourHolidaySummaryWiWindow UIYourHolidaySummaryWiWindow
        {
            get
            {
                if ((this.mUIYourHolidaySummaryWiWindow == null))
                {
                    this.mUIYourHolidaySummaryWiWindow = new UIYourHolidaySummaryWiWindow();
                }
                return this.mUIYourHolidaySummaryWiWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyHSPKOpened_MethodExpectedValues mverifyHSPKOpened_MethodExpectedValues;
        
        private UIYourHolidaySummaryWiWindow mUIYourHolidaySummaryWiWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyHSPKOpened_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class verifyHSPKOpened_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Your Holiday Summary' pane equals 'Your Holiday Summary'
        /// </summary>
        public string UIYourHolidaySummaryPaneInnerText = "Your Holiday Summary";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIYourHolidaySummaryWiWindow : BrowserWindow
    {
        
        public UIYourHolidaySummaryWiWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Your Holiday Summary";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYourHolidaySummaryDocument UIYourHolidaySummaryDocument
        {
            get
            {
                if ((this.mUIYourHolidaySummaryDocument == null))
                {
                    this.mUIYourHolidaySummaryDocument = new UIYourHolidaySummaryDocument(this);
                }
                return this.mUIYourHolidaySummaryDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYourHolidaySummaryDocument mUIYourHolidaySummaryDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIYourHolidaySummaryDocument : HtmlDocument
    {
        
        public UIYourHolidaySummaryDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Your Holiday Summary";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/code_net/booking/default.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://nimbus1.villaplus.com/code_net/booking/default.aspx";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public UITblMainTable UITblMainTable
        {
            get
            {
                if ((this.mUITblMainTable == null))
                {
                    this.mUITblMainTable = new UITblMainTable(this);
                }
                return this.mUITblMainTable;
            }
        }
        #endregion
        
        #region Fields
        private UITblMainTable mUITblMainTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UITblMainTable : HtmlTable
    {
        
        public UITblMainTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "tblMain";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Your Holiday Summary\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nVill";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "width=\"994\" align=\"center\" id=\"tblMain\" style=\"visibility: visible; background-co" +
                "lor: rgb(255, 255, 255);\" border=\"0\" cellSpacing=\"0\" cellPadding=\"0\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIYourHolidaySummaryPane
        {
            get
            {
                if ((this.mUIYourHolidaySummaryPane == null))
                {
                    this.mUIYourHolidaySummaryPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIYourHolidaySummaryPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIYourHolidaySummaryPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIYourHolidaySummaryPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Your Holiday Summary";
                    this.mUIYourHolidaySummaryPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIYourHolidaySummaryPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "pageHeaders contentRows";
                    this.mUIYourHolidaySummaryPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"pageHeaders contentRows\"";
                    this.mUIYourHolidaySummaryPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "27";
                    this.mUIYourHolidaySummaryPane.WindowTitles.Add("Your Holiday Summary");
                    #endregion
                }
                return this.mUIYourHolidaySummaryPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIYourHolidaySummaryPane;
        #endregion
    }
}
