// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.BalancePayment.VerifyCompleteHolidayCostSection_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using System.Data.Sql;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class VerifyCompleteHolidayCostSection_Map
    {
        
        /// <summary>
        /// VerifyCompleteHolidayCostSection_Method - Use 'VerifyCompleteHolidayCostSection_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void VerifyCompleteHolidayCostSection_Method()
        {
            #region Variable Declarations
            HtmlCell uIHolidayCostCell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIHolidayCostCell;
            HtmlCell uIItem209086Cell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIItem209086Cell;
            HtmlCell uICreditChargeCell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UICreditChargeCell;
            HtmlCell uIItem1116Cell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIItem1116Cell;
            HtmlCell uITotalCostCell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UITotalCostCell;
            HtmlCell uIItem210202Cell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIItem210202Cell;
            HtmlCell uITotalPaidCell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UITotalPaidCell;
            HtmlCell uIItem56912Cell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIItem56912Cell;
            HtmlCell uIRefundCell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIRefundCell;
            HtmlCell uIItem000Cell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIItem000Cell;
            HtmlCell uIOutstandingBalanceCell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIOutstandingBalanceCell;
            HtmlCell uIItem153290Cell = this.UIVillaPlusBalancePaymWindow.UIVillaPlusBalancePaymDocument.UIFrmBalancePaymentCustom.UIItemTable.UIItem153290Cell;
            #endregion

            // Verify that the 'InnerText' property of 'Holiday Cost' cell equals 'Holiday Cost'
            Assert.AreEqual(this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIHolidayCostCellInnerText, uIHolidayCostCell.InnerText);

            // Verify that the 'InnerText' property of '£2090.86' cell contains '£2090.86'
            StringAssert.Contains(uIItem209086Cell.InnerText, this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIItem209086CellInnerText);

            // Verify that the 'InnerText' property of 'Credit Charge' cell equals 'Credit Charge'
            Assert.AreEqual(this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UICreditChargeCellInnerText, uICreditChargeCell.InnerText);

            // Verify that the 'InnerText' property of '£11.16' cell contains '£11.16'
            StringAssert.Contains(uIItem1116Cell.InnerText, this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIItem1116CellInnerText);

            // Verify that the 'InnerText' property of 'Total Cost' cell equals 'Total Cost'
            Assert.AreEqual(this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UITotalCostCellInnerText, uITotalCostCell.InnerText);

            // Verify that the 'InnerText' property of '£2102.02' cell contains '£2102.02'
            StringAssert.Contains(uIItem210202Cell.InnerText, this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIItem210202CellInnerText);

            // Verify that the 'InnerText' property of 'Total Paid' cell equals 'Total Paid'
            Assert.AreEqual(this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UITotalPaidCellInnerText, uITotalPaidCell.InnerText);

            // Verify that the 'InnerText' property of '£569.12' cell contains '£569.12'
            StringAssert.Contains(uIItem56912Cell.InnerText, this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIItem56912CellInnerText);

            // Verify that the 'InnerText' property of 'Refund' cell equals 'Refund'
            Assert.AreEqual(this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIRefundCellInnerText, uIRefundCell.InnerText);

            // Verify that the 'InnerText' property of '£0.00' cell contains '£0.00'
            StringAssert.Contains(uIItem000Cell.InnerText, this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIItem000CellInnerText);

            // Verify that the 'InnerText' property of 'Outstanding Balance' cell equals 'Outstanding Balance'
            Assert.AreEqual(this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIOutstandingBalanceCellInnerText, uIOutstandingBalanceCell.InnerText);

            // Verify that the 'InnerText' property of '£1532.90' cell contains '£1532.90'
            StringAssert.Contains(uIItem153290Cell.InnerText, this.VerifyCompleteHolidayCostSection_MethodExpectedValues.UIItem153290CellInnerText);
        }
        
        #region Properties
        public virtual VerifyCompleteHolidayCostSection_MethodExpectedValues VerifyCompleteHolidayCostSection_MethodExpectedValues
        {
            get
            {
                if ((this.mVerifyCompleteHolidayCostSection_MethodExpectedValues == null))
                {
                    this.mVerifyCompleteHolidayCostSection_MethodExpectedValues = new VerifyCompleteHolidayCostSection_MethodExpectedValues();
                }
                return this.mVerifyCompleteHolidayCostSection_MethodExpectedValues;
            }
        }
        
        public UIVillaPlusBalancePaymWindow UIVillaPlusBalancePaymWindow
        {
            get
            {
                if ((this.mUIVillaPlusBalancePaymWindow == null))
                {
                    this.mUIVillaPlusBalancePaymWindow = new UIVillaPlusBalancePaymWindow();
                }
                return this.mUIVillaPlusBalancePaymWindow;
            }
        }
        #endregion
        
        #region Fields
        private VerifyCompleteHolidayCostSection_MethodExpectedValues mVerifyCompleteHolidayCostSection_MethodExpectedValues;
        
        private UIVillaPlusBalancePaymWindow mUIVillaPlusBalancePaymWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifyCompleteHolidayCostSection_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class VerifyCompleteHolidayCostSection_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Holiday Cost' cell equals 'Holiday Cost'
        /// </summary>
        public string UIHolidayCostCellInnerText = "Holiday Cost";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '£2090.86' cell contains '£2090.86'
        /// </summary>
        public string UIItem209086CellInnerText = "£2090.86";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Credit Charge' cell equals 'Credit Charge'
        /// </summary>
        public string UICreditChargeCellInnerText = "Credit Charge";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '£11.16' cell contains '£11.16'
        /// </summary>
        public string UIItem1116CellInnerText = "£11.16";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Total Cost' cell equals 'Total Cost'
        /// </summary>
        public string UITotalCostCellInnerText = "Total Cost";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '£2102.02' cell contains '£2102.02'
        /// </summary>
        public string UIItem210202CellInnerText = "£2102.02";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Total Paid' cell equals 'Total Paid'
        /// </summary>
        public string UITotalPaidCellInnerText = "Total Paid";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '£569.12' cell contains '£569.12'
        /// </summary>
        public string UIItem56912CellInnerText = "£569.12";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Refund' cell equals 'Refund'
        /// </summary>
        public string UIRefundCellInnerText = "Refund";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '£0.00' cell contains '£0.00'
        /// </summary>
        public string UIItem000CellInnerText = "£0.00";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Outstanding Balance' cell equals 'Outstanding Balance'
        /// </summary>
        public string UIOutstandingBalanceCellInnerText = "Outstanding Balance";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '£1532.90' cell contains '£1532.90'
        /// </summary>
        public string UIItem153290CellInnerText = "£1532.90";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIVillaPlusBalancePaymWindow : BrowserWindow
    {
        
        public UIVillaPlusBalancePaymWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusBalancePaymDocument UIVillaPlusBalancePaymDocument
        {
            get
            {
                if ((this.mUIVillaPlusBalancePaymDocument == null))
                {
                    this.mUIVillaPlusBalancePaymDocument = new UIVillaPlusBalancePaymDocument(this);
                }
                return this.mUIVillaPlusBalancePaymDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusBalancePaymDocument mUIVillaPlusBalancePaymDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIVillaPlusBalancePaymDocument : HtmlDocument
    {
        
        public UIVillaPlusBalancePaymDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Plus Balance Payment";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/balancepayments/default.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.villaplus.com/balancepayments/default.aspx?id=kgjorqnCk9QOQEbMWflsLQ=" +
                "=";
            this.WindowTitles.Add("Villa Plus Balance Payment");
            #endregion
        }
        
        #region Properties
        public UIFrmBalancePaymentCustom UIFrmBalancePaymentCustom
        {
            get
            {
                if ((this.mUIFrmBalancePaymentCustom == null))
                {
                    this.mUIFrmBalancePaymentCustom = new UIFrmBalancePaymentCustom(this);
                }
                return this.mUIFrmBalancePaymentCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIFrmBalancePaymentCustom mUIFrmBalancePaymentCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFrmBalancePaymentCustom : HtmlCustom
    {
        
        public UIFrmBalancePaymentCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "frmBalancePayment";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"frmBalancePayment\" onsubmit=\"javascr";
            this.FilterProperties["TagInstance"] = "1";
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties.Add(new PropertyExpression(HtmlTable.PropertyNames.InnerText, "Holiday Cost", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "width=\"220\" border=\"0\" cellSpacing=\"0\" cellPadding=\"0\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "22";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "5";
            #endregion
        }
        
        #region Properties
        public HtmlCell UIHolidayCostCell
        {
            get
            {
                if ((this.mUIHolidayCostCell == null))
                {
                    this.mUIHolidayCostCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIHolidayCostCell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIHolidayCostCell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIHolidayCostCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIHolidayCostCell.SearchProperties.Add(new PropertyExpression(HtmlCell.PropertyNames.InnerText, "Holiday Cost", PropertyExpressionOperator.Contains));
                    this.mUIHolidayCostCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"left\" class=\"boldText\"";
                    this.mUIHolidayCostCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIHolidayCostCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIHolidayCostCell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIHolidayCostCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "19";
                    #endregion
                }
                return this.mUIHolidayCostCell;
            }
        }
        
        public HtmlCell UIItem209086Cell
        {
            get
            {
                if ((this.mUIItem209086Cell == null))
                {
                    this.mUIItem209086Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem209086Cell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIItem209086Cell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIItem209086Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem209086Cell.SearchProperties.Add(new PropertyExpression(HtmlCell.PropertyNames.InnerText, "£", PropertyExpressionOperator.Contains));
                    this.mUIItem209086Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"right\" class=\"boldText\"";
                    this.mUIItem209086Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItem209086Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem209086Cell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIItem209086Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "21";
                    #endregion
                }
                return this.mUIItem209086Cell;
            }
        }
        
        public HtmlCell UICreditChargeCell
        {
            get
            {
                if ((this.mUICreditChargeCell == null))
                {
                    this.mUICreditChargeCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUICreditChargeCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUICreditChargeCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUICreditChargeCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUICreditChargeCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Credit Charge";
                    this.mUICreditChargeCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"left\" class=\"boldText\"";
                    this.mUICreditChargeCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUICreditChargeCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUICreditChargeCell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUICreditChargeCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "23";
                    #endregion
                }
                return this.mUICreditChargeCell;
            }
        }
        
        public HtmlCell UIItem1116Cell
        {
            get
            {
                if ((this.mUIItem1116Cell == null))
                {
                    this.mUIItem1116Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem1116Cell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIItem1116Cell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIItem1116Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem1116Cell.SearchProperties.Add(new PropertyExpression(HtmlCell.PropertyNames.InnerText, "£", PropertyExpressionOperator.Contains));
                    this.mUIItem1116Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"right\" class=\"boldText\"";
                    this.mUIItem1116Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIItem1116Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem1116Cell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIItem1116Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "25";
                    #endregion
                }
                return this.mUIItem1116Cell;
            }
        }
        
        public HtmlCell UITotalCostCell
        {
            get
            {
                if ((this.mUITotalCostCell == null))
                {
                    this.mUITotalCostCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUITotalCostCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUITotalCostCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUITotalCostCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUITotalCostCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Total Cost";
                    this.mUITotalCostCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"left\" class=\"boldText\"";
                    this.mUITotalCostCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "6";
                    this.mUITotalCostCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUITotalCostCell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUITotalCostCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "29";
                    #endregion
                }
                return this.mUITotalCostCell;
            }
        }
        
        public HtmlCell UIItem210202Cell
        {
            get
            {
                if ((this.mUIItem210202Cell == null))
                {
                    this.mUIItem210202Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem210202Cell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIItem210202Cell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIItem210202Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem210202Cell.SearchProperties.Add(new PropertyExpression(HtmlCell.PropertyNames.InnerText, "£", PropertyExpressionOperator.Contains));
                    this.mUIItem210202Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"right\" class=\"boldText\"";
                    this.mUIItem210202Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "6";
                    this.mUIItem210202Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem210202Cell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIItem210202Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "31";
                    #endregion
                }
                return this.mUIItem210202Cell;
            }
        }
        
        public HtmlCell UITotalPaidCell
        {
            get
            {
                if ((this.mUITotalPaidCell == null))
                {
                    this.mUITotalPaidCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUITotalPaidCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUITotalPaidCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUITotalPaidCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUITotalPaidCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Total Paid";
                    this.mUITotalPaidCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"left\" class=\"boldText\"";
                    this.mUITotalPaidCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "10";
                    this.mUITotalPaidCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUITotalPaidCell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUITotalPaidCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "35";
                    #endregion
                }
                return this.mUITotalPaidCell;
            }
        }
        
        public HtmlCell UIItem56912Cell
        {
            get
            {
                if ((this.mUIItem56912Cell == null))
                {
                    this.mUIItem56912Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem56912Cell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIItem56912Cell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIItem56912Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem56912Cell.SearchProperties.Add(new PropertyExpression(HtmlCell.PropertyNames.InnerText, "£", PropertyExpressionOperator.Contains));
                    this.mUIItem56912Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"right\" class=\"boldText\"";
                    this.mUIItem56912Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "10";
                    this.mUIItem56912Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem56912Cell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIItem56912Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "37";
                    #endregion
                }
                return this.mUIItem56912Cell;
            }
        }
        
        public HtmlCell UIRefundCell
        {
            get
            {
                if ((this.mUIRefundCell == null))
                {
                    this.mUIRefundCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIRefundCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIRefundCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIRefundCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIRefundCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Refund";
                    this.mUIRefundCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"left\" class=\"boldText\"";
                    this.mUIRefundCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "12";
                    this.mUIRefundCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIRefundCell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIRefundCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "39";
                    #endregion
                }
                return this.mUIRefundCell;
            }
        }
        
        public HtmlCell UIItem000Cell
        {
            get
            {
                if ((this.mUIItem000Cell == null))
                {
                    this.mUIItem000Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem000Cell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIItem000Cell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIItem000Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem000Cell.SearchProperties.Add(new PropertyExpression(HtmlCell.PropertyNames.InnerText, "£", PropertyExpressionOperator.Contains));
                    this.mUIItem000Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"right\" class=\"boldText\"";
                    this.mUIItem000Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "12";
                    this.mUIItem000Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem000Cell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIItem000Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "41";
                    #endregion
                }
                return this.mUIItem000Cell;
            }
        }
        
        public HtmlCell UIOutstandingBalanceCell
        {
            get
            {
                if ((this.mUIOutstandingBalanceCell == null))
                {
                    this.mUIOutstandingBalanceCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIOutstandingBalanceCell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIOutstandingBalanceCell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIOutstandingBalanceCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIOutstandingBalanceCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Outstanding Balance";
                    this.mUIOutstandingBalanceCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"left\" class=\"boldText\"";
                    this.mUIOutstandingBalanceCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "16";
                    this.mUIOutstandingBalanceCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIOutstandingBalanceCell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIOutstandingBalanceCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "45";
                    #endregion
                }
                return this.mUIOutstandingBalanceCell;
            }
        }
        
        public HtmlCell UIItem153290Cell
        {
            get
            {
                if ((this.mUIItem153290Cell == null))
                {
                    this.mUIItem153290Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem153290Cell.SearchProperties[HtmlCell.PropertyNames.Id] = "";
                    this.mUIItem153290Cell.SearchProperties[HtmlCell.PropertyNames.Name] = "";
                    this.mUIItem153290Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem153290Cell.SearchProperties.Add(new PropertyExpression(HtmlCell.PropertyNames.InnerText, "£", PropertyExpressionOperator.Contains));
                    this.mUIItem153290Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "align=\"right\" class=\"boldText\"";
                    this.mUIItem153290Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "16";
                    this.mUIItem153290Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem153290Cell.FilterProperties[HtmlCell.PropertyNames.Class] = "boldText";
                    this.mUIItem153290Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "47";
                    #endregion
                }
                return this.mUIItem153290Cell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIHolidayCostCell;
        
        private HtmlCell mUIItem209086Cell;
        
        private HtmlCell mUICreditChargeCell;
        
        private HtmlCell mUIItem1116Cell;
        
        private HtmlCell mUITotalCostCell;
        
        private HtmlCell mUIItem210202Cell;
        
        private HtmlCell mUITotalPaidCell;
        
        private HtmlCell mUIItem56912Cell;
        
        private HtmlCell mUIRefundCell;
        
        private HtmlCell mUIItem000Cell;
        
        private HtmlCell mUIOutstandingBalanceCell;
        
        private HtmlCell mUIItem153290Cell;
        #endregion
    }
}
