// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.TabSearchTile.enterNumofInfantsinTab_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class enterNumofInfantsinTab_Map:logWriter
    {
        
        /// <summary>
        /// enterNumofInfantsinTab_Method - Use 'enterNumofInfantsinTab_MethodParams' to pass parameters into this method.
        /// </summary>
        public int enterNumofInfantsinTab_Method(int MaxOCCUPANCY)
        {
            #region Variable Declarations
            HtmlEdit uIItemEdit = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UIInfantsPane.UIItemEdit;
            #endregion

            //int Numofitems = MaxOCCUPANCY / 2;
            int Numofitems = 3;
            Random rnd = new Random();
            int randomInfantsNum = rnd.Next(1, Numofitems);
            int NumofInfantsSelected = 0;

            try
            {
                // Type '1' in text box
                uIItemEdit.Text =Convert.ToString(randomInfantsNum);
                NumofInfantsSelected = randomInfantsNum;
                WriteLogs("PASS : \"" + NumofInfantsSelected + "\" Infants Selected.");
            }
            catch (AssertFailedException ex)
            {
                takeImage("enterNumofInfantsinTab");
                WriteLogs("FAIL : Could Not Select Num of Infants in Tablet Search Tile.");
                WriteLogs("-----------------" + ex.Message.ToString());
            }
            return NumofInfantsSelected;
        }
        
        #region Properties
        public virtual enterNumofInfantsinTab_MethodParams enterNumofInfantsinTab_MethodParams
        {
            get
            {
                if ((this.menterNumofInfantsinTab_MethodParams == null))
                {
                    this.menterNumofInfantsinTab_MethodParams = new enterNumofInfantsinTab_MethodParams();
                }
                return this.menterNumofInfantsinTab_MethodParams;
            }
        }
        
        public UIVillaHolidaysThatYouWindow UIVillaHolidaysThatYouWindow
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouWindow == null))
                {
                    this.mUIVillaHolidaysThatYouWindow = new UIVillaHolidaysThatYouWindow();
                }
                return this.mUIVillaHolidaysThatYouWindow;
            }
        }
        #endregion
        
        #region Fields
        private enterNumofInfantsinTab_MethodParams menterNumofInfantsinTab_MethodParams;
        
        private UIVillaHolidaysThatYouWindow mUIVillaHolidaysThatYouWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'enterNumofInfantsinTab_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class enterNumofInfantsinTab_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Type '1' in text box
        /// </summary>
        public string UIItemEditText = "1";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaHolidaysThatYouWindow : BrowserWindow
    {
        
        public UIVillaHolidaysThatYouWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaHolidaysThatYouDocument UIVillaHolidaysThatYouDocument
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument == null))
                {
                    this.mUIVillaHolidaysThatYouDocument = new UIVillaHolidaysThatYouDocument(this);
                }
                return this.mUIVillaHolidaysThatYouDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouDocument mUIVillaHolidaysThatYouDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaHolidaysThatYouDocument : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UIInfantsPane UIInfantsPane
        {
            get
            {
                if ((this.mUIInfantsPane == null))
                {
                    this.mUIInfantsPane = new UIInfantsPane(this);
                }
                return this.mUIInfantsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIInfantsPane mUIInfantsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIInfantsPane : HtmlDiv
    {
        
        public UIInfantsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "divInfants";
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Infants";
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "spinnerContainer";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"spinnerContainer\" id=\"divInfants\" style=\"width: 185px; height: 35px;\"";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "spinnerTextInput calendarHeaders";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"spinnerTextInput calendarHeaders\"";
                    this.mUIItemEdit.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIItemEdit;
        #endregion
    }
}
