// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.OtherPaxPage.enterInfantFNames_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class enterInfantFNames_Map
    {
        
        /// <summary>
        /// enterInfantFNames_Method - Use 'enterInfantFNames_MethodParams' to pass parameters into this method.
        /// </summary>
        public void enterInfantFNames_Method()
        {
            #region Variable Declarations
            HtmlEdit uITxtInfantFNameEdit = this.UIOtherPassengersDetaiWindow.UIOtherPassengersDetaiDocument.UITxtInfantFNameEdit;
            #endregion

            // Type 'Infant FName' in 'txtInfantFName' text box
            uITxtInfantFNameEdit.Text = this.enterInfantFNames_MethodParams.UITxtInfantFNameEditText;
        }

        public HtmlEdit getInfantFNames_Method()
        {
            #region Variable Declarations
            HtmlEdit uITxtInfantFNameEdit = this.UIOtherPassengersDetaiWindow.UIOtherPassengersDetaiDocument.UITxtInfantFNameEdit;
            #endregion

            // Type 'Infant FName' in 'txtInfantFName' text box
            //uITxtInfantFNameEdit.Text = this.enterInfantFNames_MethodParams.UITxtInfantFNameEditText;
            return uITxtInfantFNameEdit;
        }

        #region Properties
        public virtual enterInfantFNames_MethodParams enterInfantFNames_MethodParams
        {
            get
            {
                if ((this.menterInfantFNames_MethodParams == null))
                {
                    this.menterInfantFNames_MethodParams = new enterInfantFNames_MethodParams();
                }
                return this.menterInfantFNames_MethodParams;
            }
        }
        
        public UIOtherPassengersDetaiWindow UIOtherPassengersDetaiWindow
        {
            get
            {
                if ((this.mUIOtherPassengersDetaiWindow == null))
                {
                    this.mUIOtherPassengersDetaiWindow = new UIOtherPassengersDetaiWindow();
                }
                return this.mUIOtherPassengersDetaiWindow;
            }
        }
        #endregion
        
        #region Fields
        private enterInfantFNames_MethodParams menterInfantFNames_MethodParams;
        
        private UIOtherPassengersDetaiWindow mUIOtherPassengersDetaiWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'enterInfantFNames_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class enterInfantFNames_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Infant FName' in 'txtInfantFName' text box
        /// </summary>
        public string UITxtInfantFNameEditText = "Infant FName";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIOtherPassengersDetaiWindow : BrowserWindow
    {
        
        public UIOtherPassengersDetaiWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Other Passengers Details", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Other Passengers Details");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIOtherPassengersDetaiDocument UIOtherPassengersDetaiDocument
        {
            get
            {
                if ((this.mUIOtherPassengersDetaiDocument == null))
                {
                    this.mUIOtherPassengersDetaiDocument = new UIOtherPassengersDetaiDocument(this);
                }
                return this.mUIOtherPassengersDetaiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOtherPassengersDetaiDocument mUIOtherPassengersDetaiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIOtherPassengersDetaiDocument : HtmlDocument
    {
        
        public UIOtherPassengersDetaiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Other Passengers Details", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/booking/allocatePax.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/allocatePax.aspx", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Other Passengers Details");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UITxtInfantFNameEdit
        {
            get
            {
                if ((this.mUITxtInfantFNameEdit == null))
                {
                    this.mUITxtInfantFNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITxtInfantFNameEdit.SearchProperties.Add(new PropertyExpression(HtmlEdit.PropertyNames.Id, "txtInfantFName", PropertyExpressionOperator.Contains));
                    this.mUITxtInfantFNameEdit.SearchProperties.Add(new PropertyExpression(HtmlEdit.PropertyNames.Name, "$txtInfantFName", PropertyExpressionOperator.Contains));
                    this.mUITxtInfantFNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITxtInfantFNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "greyText";
                    this.mUITxtInfantFNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"FlightRepeater$ctl01$reptInfant$ct";
                    this.mUITxtInfantFNameEdit.WindowTitles.Add("Other Passengers Details");
                    #endregion
                }
                return this.mUITxtInfantFNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUITxtInfantFNameEdit;
        #endregion
    }
}
