// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.ProvConfPage.clickOKFromBookingCondPopup_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class clickOKFromBookingCondPopup_Map:logWriter
    {
        
        /// <summary>
        /// clickOKFromBookingCondPopup_Method
        /// </summary>
        public void clickOKFromBookingCondPopup_Method()
        {
            #region Variable Declarations
            HtmlImage uIOKImage = this.UIVillaPlusHolidayBookWindow.UIVillaPlusHolidayBookDocument.UIIfrmTermsAndConditioFrame.UIVillaPlusQualityholiDocument.UIOKImage;
            HtmlImage uIOKImage1 = this.UIVillaPlusHolidayBookWindow.UIVillaPlusHolidayBookDocument.UIIfrmTermsAndConditioFrame.UIVillaPlusQualityholiDocument.UIOKImage1;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Ok' image at (47, 8)
            Mouse.Hover(uIOKImage, new Point(47, 8));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Ok' image
            Mouse.Click(uIOKImage1, new Point(38, 12));
        }
        
        #region Properties
        public UIVillaPlusHolidayBookWindow UIVillaPlusHolidayBookWindow
        {
            get
            {
                if ((this.mUIVillaPlusHolidayBookWindow == null))
                {
                    this.mUIVillaPlusHolidayBookWindow = new UIVillaPlusHolidayBookWindow();
                }
                return this.mUIVillaPlusHolidayBookWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusHolidayBookWindow mUIVillaPlusHolidayBookWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaPlusHolidayBookWindow : BrowserWindow
    {
        
        public UIVillaPlusHolidayBookWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus - Holiday Booking Details", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus - Holiday Booking Details");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusHolidayBookDocument UIVillaPlusHolidayBookDocument
        {
            get
            {
                if ((this.mUIVillaPlusHolidayBookDocument == null))
                {
                    this.mUIVillaPlusHolidayBookDocument = new UIVillaPlusHolidayBookDocument(this);
                }
                return this.mUIVillaPlusHolidayBookDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusHolidayBookDocument mUIVillaPlusHolidayBookDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaPlusHolidayBookDocument : HtmlDocument
    {
        
        public UIVillaPlusHolidayBookDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus - Holiday Booking Details", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/booking/bookingstatus.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/bookingstatus.aspx", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus - Holiday Booking Details");
            #endregion
        }
        
        #region Properties
        public UIIfrmTermsAndConditioFrame UIIfrmTermsAndConditioFrame
        {
            get
            {
                if ((this.mUIIfrmTermsAndConditioFrame == null))
                {
                    this.mUIIfrmTermsAndConditioFrame = new UIIfrmTermsAndConditioFrame(this);
                }
                return this.mUIIfrmTermsAndConditioFrame;
            }
        }
        #endregion
        
        #region Fields
        private UIIfrmTermsAndConditioFrame mUIIfrmTermsAndConditioFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIIfrmTermsAndConditioFrame : HtmlIFrame
    {
        
        public UIIfrmTermsAndConditioFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "ifrmTermsAndConditions";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/code_net/common/termsandconditions.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=\"ifrmTermsAndConditions\" src=\"/code_n";
            this.WindowTitles.Add("Villa Plus - Holiday Booking Details");
            #endregion
        }
        
        #region Properties
        public UIVillaPlusQualityholiDocument UIVillaPlusQualityholiDocument
        {
            get
            {
                if ((this.mUIVillaPlusQualityholiDocument == null))
                {
                    this.mUIVillaPlusQualityholiDocument = new UIVillaPlusQualityholiDocument(this);
                }
                return this.mUIVillaPlusQualityholiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusQualityholiDocument mUIVillaPlusQualityholiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaPlusQualityholiDocument : HtmlDocument
    {
        
        public UIVillaPlusQualityholiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus - Quality holiday villas with private pools", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/common/termsandconditions.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/common/termsandconditions.aspx", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus - Holiday Booking Details");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIOKImage
        {
            get
            {
                if ((this.mUIOKImage == null))
                {
                    this.mUIOKImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Id] = "cmdOkOFF";
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Ok";
                    this.mUIOKImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.AbsolutePath, "/imgs/vp/buttons/okON.gif", PropertyExpressionOperator.Contains));
                    this.mUIOKImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "/imgs/vp/buttons/okON.gif", PropertyExpressionOperator.Contains));
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "title=\"Ok\" id=\"cmdOkOFF\" alt=\"Ok\" src=\"/";
                    this.mUIOKImage.WindowTitles.Add("Villa Plus - Holiday Booking Details");
                    #endregion
                }
                return this.mUIOKImage;
            }
        }
        
        public HtmlImage UIOKImage1
        {
            get
            {
                if ((this.mUIOKImage1 == null))
                {
                    this.mUIOKImage1 = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIOKImage1.SearchProperties[HtmlImage.PropertyNames.Id] = "cmdOkOn";
                    this.mUIOKImage1.SearchProperties[HtmlImage.PropertyNames.Alt] = "Ok";
                    this.mUIOKImage1.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.AbsolutePath, "/imgs/vp/buttons/okOFF.gif", PropertyExpressionOperator.Contains));
                    this.mUIOKImage1.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "/imgs/vp/buttons/okOFF.gif", PropertyExpressionOperator.Contains));
                    this.mUIOKImage1.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "title=\"Ok\" id=\"cmdOkOn\" style=\"border: 0";
                    this.mUIOKImage1.WindowTitles.Add("Villa Plus - Holiday Booking Details");
                    #endregion
                }
                return this.mUIOKImage1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIOKImage;
        
        private HtmlImage mUIOKImage1;
        #endregion
    }
}
