// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.BookingPages.AddAmendCarHire.clickDeleteBtnForCar_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class clickDeleteBtnForCar_Map:logWriter
    {
        
        /// <summary>
        /// clickDeleteBtnForCar_Method
        /// </summary>
        public void clickDeleteBtnForCar_Method()
        {
            #region Variable Declarations
            HtmlDiv uIDeletePane = this.UIYourHolidaySummaryWiWindow.UIYourHolidaySummaryDocument.UIAmendCarHireFrame.UIAmendCarHireDocument.UIDeletePane;
            #endregion

            try
            {
                // Click 'Delete' pane
                Mouse.Click(uIDeletePane, new Point(37, 17));
                WriteLogs("PASS : Clicked \"Delete\" Button For a Car.");
            }
            catch (AssertFailedException ex)
            {
                takeImage("clickDeleteBtnForCar");
                WriteLogs("FAIL : Could Not click \"Delete\" Button For Car.");
                WriteLogs("-----------------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIYourHolidaySummaryWiWindow UIYourHolidaySummaryWiWindow
        {
            get
            {
                if ((this.mUIYourHolidaySummaryWiWindow == null))
                {
                    this.mUIYourHolidaySummaryWiWindow = new UIYourHolidaySummaryWiWindow();
                }
                return this.mUIYourHolidaySummaryWiWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYourHolidaySummaryWiWindow mUIYourHolidaySummaryWiWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIYourHolidaySummaryWiWindow : BrowserWindow
    {
        
        public UIYourHolidaySummaryWiWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Your Holiday Summary", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYourHolidaySummaryDocument UIYourHolidaySummaryDocument
        {
            get
            {
                if ((this.mUIYourHolidaySummaryDocument == null))
                {
                    this.mUIYourHolidaySummaryDocument = new UIYourHolidaySummaryDocument(this);
                }
                return this.mUIYourHolidaySummaryDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYourHolidaySummaryDocument mUIYourHolidaySummaryDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIYourHolidaySummaryDocument : HtmlDocument
    {
        
        public UIYourHolidaySummaryDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Your Holiday Summary", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/booking/default.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/default.aspx", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public UIAmendCarHireFrame UIAmendCarHireFrame
        {
            get
            {
                if ((this.mUIAmendCarHireFrame == null))
                {
                    this.mUIAmendCarHireFrame = new UIAmendCarHireFrame(this);
                }
                return this.mUIAmendCarHireFrame;
            }
        }
        #endregion
        
        #region Fields
        private UIAmendCarHireFrame mUIAmendCarHireFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAmendCarHireFrame : HtmlIFrame
    {
        
        public UIAmendCarHireFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "amendCarHire";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = "amendCarHire";
            this.FilterProperties.Add(new PropertyExpression(HtmlFrame.PropertyNames.AbsolutePath, "amendCarHire.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlFrame.PropertyNames.PageUrl, "amendCarHire.aspx?", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "name=\"amendCarHire\" id=\"amendCarHire\" sr";
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public UIAmendCarHireDocument UIAmendCarHireDocument
        {
            get
            {
                if ((this.mUIAmendCarHireDocument == null))
                {
                    this.mUIAmendCarHireDocument = new UIAmendCarHireDocument(this);
                }
                return this.mUIAmendCarHireDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAmendCarHireDocument mUIAmendCarHireDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAmendCarHireDocument : HtmlDocument
    {
        
        public UIAmendCarHireDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Amend Car Hire", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/code_net/booking/amendCarHire.aspx", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/code_net/booking/amendCarHire.aspx?refNo=", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your Holiday Summary");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIDeletePane
        {
            get
            {
                if ((this.mUIDeletePane == null))
                {
                    this.mUIDeletePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDeletePane.SearchProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Id, "DeleteCar_", PropertyExpressionOperator.Contains));
                    this.mUIDeletePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Delete";
                    this.mUIDeletePane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Class, "mycell orangeButtons cmdSelectACar", PropertyExpressionOperator.Contains));
                    this.mUIDeletePane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"mycell orangeButtons cmdSelectACar\"", PropertyExpressionOperator.Contains));
                    this.mUIDeletePane.WindowTitles.Add("Your Holiday Summary");
                    #endregion
                }
                return this.mUIDeletePane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIDeletePane;
        #endregion
    }
}
