// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.ProductPage.clickVillaNFlightsBtnFrmProductPage_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class clickVillaNFlightsBtnFrmProductPage_Map
    {
        
        /// <summary>
        /// clickVillaNFlightsBtnFrmProductPage_Method
        /// </summary>
        public void clickVillaNFlightsBtnFrmProductPage_Method()
        {
            #region Variable Declarations
            HtmlInputButton uIBookvillaflightsButton = this.UIVillaBrisasMarInCorrWindow.UIVillaBrisasMarInCorrDocument.UIBookvillaflightsButton;
            #endregion

            // Click 'Book villa & flights' button
            Mouse.Click(uIBookvillaflightsButton, new Point(62, 7));
        }
        
        #region Properties
        public UIVillaBrisasMarInCorrWindow UIVillaBrisasMarInCorrWindow
        {
            get
            {
                if ((this.mUIVillaBrisasMarInCorrWindow == null))
                {
                    this.mUIVillaBrisasMarInCorrWindow = new UIVillaBrisasMarInCorrWindow();
                }
                return this.mUIVillaBrisasMarInCorrWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaBrisasMarInCorrWindow mUIVillaBrisasMarInCorrWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaBrisasMarInCorrWindow : BrowserWindow
    {
        
        public UIVillaBrisasMarInCorrWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Brisas Mar In Corralejo, Fuerteventura | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaBrisasMarInCorrDocument UIVillaBrisasMarInCorrDocument
        {
            get
            {
                if ((this.mUIVillaBrisasMarInCorrDocument == null))
                {
                    this.mUIVillaBrisasMarInCorrDocument = new UIVillaBrisasMarInCorrDocument(this);
                }
                return this.mUIVillaBrisasMarInCorrDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaBrisasMarInCorrDocument mUIVillaBrisasMarInCorrDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaBrisasMarInCorrDocument : HtmlDocument
    {
        
        public UIVillaBrisasMarInCorrDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/villas/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/villas/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Brisas Mar In Corralejo, Fuerteventura | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIBookvillaflightsButton
        {
            get
            {
                if ((this.mUIBookvillaflightsButton == null))
                {
                    this.mUIBookvillaflightsButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIBookvillaflightsButton.SearchProperties[HtmlButton.PropertyNames.Id] = "MainContent_villaPriceLayer_btnBookVillaNFlight";
                    this.mUIBookvillaflightsButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$MainContent$villaPriceLayer$btnBookVillaNFlight";
                    this.mUIBookvillaflightsButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Book villa & flights";
                    this.mUIBookvillaflightsButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIBookvillaflightsButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Book villa & flights";
                    this.mUIBookvillaflightsButton.FilterProperties[HtmlButton.PropertyNames.Class] = "button font12 bold";
                    this.mUIBookvillaflightsButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$villaPriceLayer$";
                    this.mUIBookvillaflightsButton.WindowTitles.Add("Villa Brisas Mar In Corralejo, Fuerteventura | Villa Plus");
                    #endregion
                }
                return this.mUIBookvillaflightsButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIBookvillaflightsButton;
        #endregion
    }
}
