// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.ProductPage.clickOKfromIncorrectPop2_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class clickOKfromIncorrectPop2_Map:logWriter
    {
        
        /// <summary>
        /// clickOKfromIncorrectPop2_Method
        /// </summary>
        public void clickOKfromIncorrectPop2_Method()
        {
            #region Variable Declarations
            HtmlButton uIOKButton = this.UIVillaDoraInSesmariasWindow.UIVillaDoraInSesmariasDocument.UIOKButton;
            #endregion

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(9, 13));
        }
        
        #region Properties
        public UIVillaDoraInSesmariasWindow UIVillaDoraInSesmariasWindow
        {
            get
            {
                if ((this.mUIVillaDoraInSesmariasWindow == null))
                {
                    this.mUIVillaDoraInSesmariasWindow = new UIVillaDoraInSesmariasWindow();
                }
                return this.mUIVillaDoraInSesmariasWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaDoraInSesmariasWindow mUIVillaDoraInSesmariasWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaDoraInSesmariasWindow : BrowserWindow
    {
        
        public UIVillaDoraInSesmariasWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Dora In Sesmarias, Algarve | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaDoraInSesmariasDocument UIVillaDoraInSesmariasDocument
        {
            get
            {
                if ((this.mUIVillaDoraInSesmariasDocument == null))
                {
                    this.mUIVillaDoraInSesmariasDocument = new UIVillaDoraInSesmariasDocument(this);
                }
                return this.mUIVillaDoraInSesmariasDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaDoraInSesmariasDocument mUIVillaDoraInSesmariasDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaDoraInSesmariasDocument : HtmlDocument
    {
        
        public UIVillaDoraInSesmariasDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/villas/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/villas/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Dora In Sesmarias, Algarve | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "OK";
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIOKButton.FilterProperties.Add(new PropertyExpression(HtmlButton.PropertyNames.Class, "button", PropertyExpressionOperator.Contains));
                    this.mUIOKButton.FilterProperties.Add(new PropertyExpression(HtmlButton.PropertyNames.ControlDefinition, "value=\"OK\"", PropertyExpressionOperator.Contains));
                    this.mUIOKButton.WindowTitles.Add("Villa Dora In Sesmarias, Algarve | Villa Plus");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUIOKButton;
        #endregion
    }
}
