// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.ProductPage.selectActTabDepartsOn_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class selectActTabDepartsOn_Map
    {
        
        /// <summary>
        /// selectActTabDepartsOn_Method - Use 'selectActTabDepartsOn_MethodParams' to pass parameters into this method.
        /// </summary>
        public void selectActTabDepartsOn_Method()
        {
            #region Variable Declarations
            HtmlComboBox uIDdCalenderMonthsComboBox = this.UICanas1bdrmEQuintadoLWindow.UICanas1bdrmEQuintadoLDocument.UIDdCalenderMonthsComboBox;
            #endregion
            
            // Select 'June 2013' in 'ddCalenderMonths' combo box
            uIDdCalenderMonthsComboBox.SelectedItem = this.selectActTabDepartsOn_MethodParams.UIDdCalenderMonthsComboBoxSelectedItem;
        }

        public HtmlComboBox getCombo_Method()
        {
            HtmlComboBox uIDdCalenderMonthsComboBox = this.UICanas1bdrmEQuintadoLWindow.UICanas1bdrmEQuintadoLDocument.UIDdCalenderMonthsComboBox;
            return uIDdCalenderMonthsComboBox;
        }

        #region Properties
        public virtual selectActTabDepartsOn_MethodParams selectActTabDepartsOn_MethodParams
        {
            get
            {
                if ((this.mselectActTabDepartsOn_MethodParams == null))
                {
                    this.mselectActTabDepartsOn_MethodParams = new selectActTabDepartsOn_MethodParams();
                }
                return this.mselectActTabDepartsOn_MethodParams;
            }
        }
        
        public UICanas1bdrmEQuintadoLWindow UICanas1bdrmEQuintadoLWindow
        {
            get
            {
                if ((this.mUICanas1bdrmEQuintadoLWindow == null))
                {
                    this.mUICanas1bdrmEQuintadoLWindow = new UICanas1bdrmEQuintadoLWindow();
                }
                return this.mUICanas1bdrmEQuintadoLWindow;
            }
        }
        #endregion
        
        #region Fields
        private selectActTabDepartsOn_MethodParams mselectActTabDepartsOn_MethodParams;
        
        private UICanas1bdrmEQuintadoLWindow mUICanas1bdrmEQuintadoLWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'selectActTabDepartsOn_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class selectActTabDepartsOn_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'June 2013' in 'ddCalenderMonths' combo box
        /// </summary>
        public string UIDdCalenderMonthsComboBoxSelectedItem = "June 2013";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICanas1bdrmEQuintadoLWindow : BrowserWindow
    {
        
        public UICanas1bdrmEQuintadoLWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Canas 1 bdrm E, Quinta do Lago, Algarve, Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UICanas1bdrmEQuintadoLDocument UICanas1bdrmEQuintadoLDocument
        {
            get
            {
                if ((this.mUICanas1bdrmEQuintadoLDocument == null))
                {
                    this.mUICanas1bdrmEQuintadoLDocument = new UICanas1bdrmEQuintadoLDocument(this);
                }
                return this.mUICanas1bdrmEQuintadoLDocument;
            }
        }
        #endregion
        
        #region Fields
        private UICanas1bdrmEQuintadoLDocument mUICanas1bdrmEQuintadoLDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICanas1bdrmEQuintadoLDocument : HtmlDocument
    {
        
        public UICanas1bdrmEQuintadoLDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Canas 1 bdrm E, Quinta do Lago, Algarve, Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/product.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://nimbus/product.aspx?villaid=275";
            this.WindowTitles.Add("Canas 1 bdrm E, Quinta do Lago, Algarve, Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIDdCalenderMonthsComboBox
        {
            get
            {
                if ((this.mUIDdCalenderMonthsComboBox == null))
                {
                    this.mUIDdCalenderMonthsComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIDdCalenderMonthsComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ddCalenderMonths";
                    this.mUIDdCalenderMonthsComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = null;
                    this.mUIDdCalenderMonthsComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIDdCalenderMonthsComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIDdCalenderMonthsComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIDdCalenderMonthsComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "11";
                    this.mUIDdCalenderMonthsComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "noDatesAvailableForMonth";
                    this.mUIDdCalenderMonthsComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "style=\"width: 150px;\" id=\"ddCalenderMont";
                    this.mUIDdCalenderMonthsComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIDdCalenderMonthsComboBox.WindowTitles.Add("Canas 1 bdrm E, Quinta do Lago, Algarve, Villa Plus");
                    #endregion
                }
                return this.mUIDdCalenderMonthsComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIDdCalenderMonthsComboBox;
        #endregion
    }
}
