// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.ProductPage.selectInfant_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using System.Configuration;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class selectInfant_Map
    {
        
        /// <summary>
        /// selectInfant_Method - Use 'selectInfant_MethodParams' to pass parameters into this method.
        /// </summary>
        public void selectInfant_Method()
        {
            #region Variable Declarations
            HtmlComboBox uIDdInfantsComboBox = this.UIVillaFloresSalvajeInWindow.UIVillaFloresSalvajeInDocument.UIDdInfantsComboBox;
            #endregion

            // Select '2' in 'ddInfants' combo box
            //uIDdInfantsComboBox.SelectedItem = this.selectInfant_MethodParams.UIDdInfantsComboBoxSelectedItem;
            uIDdInfantsComboBox.SelectedItem = ConfigurationManager.AppSettings["NoofInfants"].ToString();

        }

        public HtmlComboBox getInfant_Method()
        {
            #region Variable Declarations
            HtmlComboBox uIDdInfantsComboBox = this.UIVillaFloresSalvajeInWindow.UIVillaFloresSalvajeInDocument.UIDdInfantsComboBox;
            return uIDdInfantsComboBox;
            #endregion
        }
        
        #region Properties
        public virtual selectInfant_MethodParams selectInfant_MethodParams
        {
            get
            {
                if ((this.mselectInfant_MethodParams == null))
                {
                    this.mselectInfant_MethodParams = new selectInfant_MethodParams();
                }
                return this.mselectInfant_MethodParams;
            }
        }
        
        public UIVillaFloresSalvajeInWindow UIVillaFloresSalvajeInWindow
        {
            get
            {
                if ((this.mUIVillaFloresSalvajeInWindow == null))
                {
                    this.mUIVillaFloresSalvajeInWindow = new UIVillaFloresSalvajeInWindow();
                }
                return this.mUIVillaFloresSalvajeInWindow;
            }
        }
        #endregion
        
        #region Fields
        private selectInfant_MethodParams mselectInfant_MethodParams;
        
        private UIVillaFloresSalvajeInWindow mUIVillaFloresSalvajeInWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'selectInfant_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class selectInfant_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Select '2' in 'ddInfants' combo box
        /// </summary>
        public string UIDdInfantsComboBoxSelectedItem = "2";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaFloresSalvajeInWindow : BrowserWindow
    {
        
        public UIVillaFloresSalvajeInWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Flores Salvaje In Callao Salvaje, Tenerife | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaFloresSalvajeInDocument UIVillaFloresSalvajeInDocument
        {
            get
            {
                if ((this.mUIVillaFloresSalvajeInDocument == null))
                {
                    this.mUIVillaFloresSalvajeInDocument = new UIVillaFloresSalvajeInDocument(this);
                }
                return this.mUIVillaFloresSalvajeInDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaFloresSalvajeInDocument mUIVillaFloresSalvajeInDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIVillaFloresSalvajeInDocument : HtmlDocument
    {
        
        public UIVillaFloresSalvajeInDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/product.aspx?", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Flores Salvaje In Callao Salvaje, Tenerife | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIDdInfantsComboBox
        {
            get
            {
                if ((this.mUIDdInfantsComboBox == null))
                {
                    this.mUIDdInfantsComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIDdInfantsComboBox.SearchProperties.Add(new PropertyExpression(HtmlComboBox.PropertyNames.Id, "ddInfants", PropertyExpressionOperator.Contains));
                    this.mUIDdInfantsComboBox.SearchProperties.Add(new PropertyExpression(HtmlComboBox.PropertyNames.Name, "$ddInfants", PropertyExpressionOperator.Contains));
                    this.mUIDdInfantsComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$VillaAvailabilit";
                    this.mUIDdInfantsComboBox.WindowTitles.Add("Villa Flores Salvaje In Callao Salvaje, Tenerife | Villa Plus");
                    #endregion
                }
                return this.mUIDdInfantsComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIDdInfantsComboBox;
        #endregion
    }
}
