// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestAutomation.UIMap.ProductPage.verfiyPriceRangedFrom_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using TestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class verfiyPriceRangedFrom_Map:logWriter
    {
        
        /// <summary>
        /// verfiyPriceRangedFrom_Method - Use 'verfiyPriceRangedFrom_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verfiyPriceRangedFrom_Method(string villapricRangeStart, string villapricRangeEnd)
        {
            #region Variable Declarations
            HtmlDiv uIDvPricePane = this.UIVillaPoppyPolisCypruWindow.UIVillaPoppyPolisCypruDocument.UIDvPricePane;
            #endregion

            // Verify that the 'InnerText' property of 'dvPrice' pane contains 'Prices ranged from
            //From : £ 374
            //To : £ 1435'
            //StringAssert.Contains(uIDvPricePane.InnerText, this.verfiyPriceRangedFrom_MethodExpectedValues.UIDvPricePaneInnerText);
            StringAssert.Contains(uIDvPricePane.InnerText, villapricRangeStart);
            StringAssert.Contains(uIDvPricePane.InnerText, villapricRangeEnd);
        }
        
        #region Properties
        public virtual verfiyPriceRangedFrom_MethodExpectedValues verfiyPriceRangedFrom_MethodExpectedValues
        {
            get
            {
                if ((this.mverfiyPriceRangedFrom_MethodExpectedValues == null))
                {
                    this.mverfiyPriceRangedFrom_MethodExpectedValues = new verfiyPriceRangedFrom_MethodExpectedValues();
                }
                return this.mverfiyPriceRangedFrom_MethodExpectedValues;
            }
        }
        
        public UIVillaPoppyPolisCypruWindow UIVillaPoppyPolisCypruWindow
        {
            get
            {
                if ((this.mUIVillaPoppyPolisCypruWindow == null))
                {
                    this.mUIVillaPoppyPolisCypruWindow = new UIVillaPoppyPolisCypruWindow();
                }
                return this.mUIVillaPoppyPolisCypruWindow;
            }
        }
        #endregion
        
        #region Fields
        private verfiyPriceRangedFrom_MethodExpectedValues mverfiyPriceRangedFrom_MethodExpectedValues;
        
        private UIVillaPoppyPolisCypruWindow mUIVillaPoppyPolisCypruWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verfiyPriceRangedFrom_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class verfiyPriceRangedFrom_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'dvPrice' pane contains 'Prices ranged from
        ///From : £ 374
        ///To : £ 1435'
        /// </summary>
        public string UIDvPricePaneInnerText = "Prices ranged from\r\nFrom : £ 374\r\nTo : £ 1435";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIVillaPoppyPolisCypruWindow : BrowserWindow
    {
        
        public UIVillaPoppyPolisCypruWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Poppy, Polis, Cyprus, Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPoppyPolisCypruDocument UIVillaPoppyPolisCypruDocument
        {
            get
            {
                if ((this.mUIVillaPoppyPolisCypruDocument == null))
                {
                    this.mUIVillaPoppyPolisCypruDocument = new UIVillaPoppyPolisCypruDocument(this);
                }
                return this.mUIVillaPoppyPolisCypruDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPoppyPolisCypruDocument mUIVillaPoppyPolisCypruDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIVillaPoppyPolisCypruDocument : HtmlDocument
    {
        
        public UIVillaPoppyPolisCypruDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Poppy, Polis, Cyprus, Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/product.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://nimbus/product.aspx?villaid=914";
            this.WindowTitles.Add("Villa Poppy, Polis, Cyprus, Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIDvPricePane
        {
            get
            {
                if ((this.mUIDvPricePane == null))
                {
                    this.mUIDvPricePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDvPricePane.SearchProperties[HtmlDiv.PropertyNames.Id] = "dvPrice";
                    this.mUIDvPricePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDvPricePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Prices ranged from\r\nFrom : £ 374\r\nTo : £";
                    this.mUIDvPricePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDvPricePane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIDvPricePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"dvPrice\"";
                    this.mUIDvPricePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "51";
                    this.mUIDvPricePane.WindowTitles.Add("Villa Poppy, Polis, Cyprus, Villa Plus");
                    #endregion
                }
                return this.mUIDvPricePane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIDvPricePane;
        #endregion
    }
}
