// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ProductPageAutomation.UIMap.verifyocTabMAbResort_mapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using ProductPageAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class verifyocTabMAbResort_map:logWriter
    {
        
        /// <summary>
        /// verifyLocTabMAresort_Method - Use 'verifyLocTabMAresort_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyLocTabMAresort_Method(string villaResortID)
        {
            #region Variable Declarations
            HtmlHyperlink uIMoreaboutthisresortHyperlink = this.UIVillaPoppyPolisCypruWindow.UIVillaPoppyPolisCypruDocument.UIMoreaboutthisresortHyperlink;
            #endregion

            // Verify that the 'Href' property of 'More about this resort' link contains 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions("ctl00$MainContent$lnkMoreAbtResort", "", false, "", "Resort.aspx?resortID=84", false, true))'
            //StringAssert.Contains(uIMoreaboutthisresortHyperlink.Href, this.verifyLocTabMAresort_MethodExpectedValues.UIMoreaboutthisresortHyperlinkHref);
            try
            {
                StringAssert.Contains(uIMoreaboutthisresortHyperlink.Href, villaResortID);
                WriteLogs("Resort ID in hyper link : PASS");
            }
            catch (AssertFailedException ex)
            {
                WriteLogs("Resort ID in hyper link : FAIL");
            }
        }
        
        #region Properties
        public virtual verifyLocTabMAresort_MethodExpectedValues verifyLocTabMAresort_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyLocTabMAresort_MethodExpectedValues == null))
                {
                    this.mverifyLocTabMAresort_MethodExpectedValues = new verifyLocTabMAresort_MethodExpectedValues();
                }
                return this.mverifyLocTabMAresort_MethodExpectedValues;
            }
        }
        
        public UIVillaPoppyPolisCypruWindow UIVillaPoppyPolisCypruWindow
        {
            get
            {
                if ((this.mUIVillaPoppyPolisCypruWindow == null))
                {
                    this.mUIVillaPoppyPolisCypruWindow = new UIVillaPoppyPolisCypruWindow();
                }
                return this.mUIVillaPoppyPolisCypruWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyLocTabMAresort_MethodExpectedValues mverifyLocTabMAresort_MethodExpectedValues;
        
        private UIVillaPoppyPolisCypruWindow mUIVillaPoppyPolisCypruWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyLocTabMAresort_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class verifyLocTabMAresort_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Href' property of 'More about this resort' link contains 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions("ctl00$MainContent$lnkMoreAbtResort", "", false, "", "Resort.aspx?resortID=84", false, true))'
        /// </summary>
        public string UIMoreaboutthisresortHyperlinkHref = "javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(\"ctl00$MainC" +
            "ontent$lnkMoreAbtResort\", \"\", false, \"\", \"Resort.aspx?resortID=84\", false, true)" +
            ")";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIVillaPoppyPolisCypruWindow : BrowserWindow
    {
        
        public UIVillaPoppyPolisCypruWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Poppy, Polis, Cyprus, Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPoppyPolisCypruDocument UIVillaPoppyPolisCypruDocument
        {
            get
            {
                if ((this.mUIVillaPoppyPolisCypruDocument == null))
                {
                    this.mUIVillaPoppyPolisCypruDocument = new UIVillaPoppyPolisCypruDocument(this);
                }
                return this.mUIVillaPoppyPolisCypruDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPoppyPolisCypruDocument mUIVillaPoppyPolisCypruDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIVillaPoppyPolisCypruDocument : HtmlDocument
    {
        
        public UIVillaPoppyPolisCypruDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Poppy, Polis, Cyprus, Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/product.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://nimbus/product.aspx?villaid=914";
            this.WindowTitles.Add("Villa Poppy, Polis, Cyprus, Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIMoreaboutthisresortHyperlink
        {
            get
            {
                if ((this.mUIMoreaboutthisresortHyperlink == null))
                {
                    this.mUIMoreaboutthisresortHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIMoreaboutthisresortHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "MainContent_lnkMoreAbtResort";
                    this.mUIMoreaboutthisresortHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIMoreaboutthisresortHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIMoreaboutthisresortHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "More about this resort";
                    this.mUIMoreaboutthisresortHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "WebForm_DoPostBackWithOptions(new%20WebForm_PostBackOptions(%22ctl00$MainContent$" +
                        "lnkMoreAbtResort%22,%20%22%22,%20false,%20%22%22,%20%22Resort.aspx";
                    this.mUIMoreaboutthisresortHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIMoreaboutthisresortHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(\"ctl00$MainC" +
                        "ontent$lnkMoreAbtResort\", \"\", false, \"\", \"Resort.aspx?resortID=84\", false, true)" +
                        ")";
                    this.mUIMoreaboutthisresortHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "bold";
                    this.mUIMoreaboutthisresortHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"MainContent_lnkMoreAbtResort\" class=";
                    this.mUIMoreaboutthisresortHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "126";
                    this.mUIMoreaboutthisresortHyperlink.WindowTitles.Add("Villa Poppy, Polis, Cyprus, Villa Plus");
                    #endregion
                }
                return this.mUIMoreaboutthisresortHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIMoreaboutthisresortHyperlink;
        #endregion
    }
}
